modules/af-features.nf
modules/af-rna.nf

When converting to the standard `meta` value for processes, I missed a place where I needed to substitute that in, breaking the mapping of feature data. Now fixed, so feature mapping works again

Fix feature mapping

---

main.nf

This PR adds a new `project` parameter to the workflow that allows running all of the runs from a submitter as a block. As implemented, this option supersedes the `run_id` option, which seems like what we will want most of the time, but if people think it should work differently, we could change that.
I also made the `run_id` option a bit more flexible, in that it can now be used to specify library ids or sample ids as well: if any match, it will process those runs. 
Closes #14

Allow processing by project/submitter

---

bin/make_splici_fasta.R
build-index.nf
main.nf
modules/build-index.nf
nextflow.config

This PR closes #23 and #19. I moved the `build-index.nf` workflow over from `alsf-scpca/workflows` to the root directory of this repo and have streamlined the processes to only make the splici index using kmer=31. Here there are now only two processes, the first takes as input the ensembl gtf and primary assembly fasta file and uses the Rscript `make_splici_fasta.R` to grab only the spliced cDNA and intronic regions from the fasta. This script also outputs the needed tx2gene 3 column file and the corresponding mitochondrial gene list. 
The second process then takes as input the path to the splici fasta and creates the index. In this PR, I also moved the path to the splici index and the tx2gene file path as parameters in the config file and removed them from the `main.nf` file. 
In testing …

Add workflow for building index to scpca-nf

---

bin/generate_unfiltered_sce.R
modules/generate-rds.nf
nextflow.config

Closes #20. This PR adds the calculation of the `colData` and `rowData` statistics to the unfiltered output within the `generate_unfiltered_sce.R` script. To do this for the RNA counts I am using `add_cell_mito_qc()` within `scpcaTools` for the per cell statistics, to get total UMI count, number of genes detected per cell, and the mitochondrial content per cell. I then also used `scater::addPerFeatureQC()` to add in the number of counts for each gene in the `rowData`. Within the nextflow workflow, the only modification was the addition of the mitochondrial file as a paramter in the config file and then as an input to the process. 
I also made the choice to NOT use the `miQC` option here since I believe we only want that additional column on the filtered output. Additionally when playing …

Add colData and rowData to unfiltered sce object

---

bin/filter_sce_rds.R
modules/generate-rds.nf

Closes #18. This PR adds in the `colData` and `rowData` to the filtered sce object. This includes adding any per cell and per feature data for alternative experiments, if present in the filtered data. To do this, I first removed the previous `rowData` that is attached to the unfiltered data since we will want to recalculate the per gene metrics using only the cells that are present in the filtered matrix. 
We don't need to recalculate the per cell metrics here, but we did want to add in a column containing the posterior probability of each cell being compromised as calculated by `miQC`. Because we want to do this after performing filtering with `emptyDrops`, I added in a step here to calculate the model then using `miQC::filterCells()` with a `posterior_cutoff=1` add in the …

Add colData and rowData to filtered sce object

---

bin/filter_sce_rds.R
bin/generate_unfiltered_sce.R
bin/sce_qc_report.R
main.nf
modules/generate-rds.nf
modules/qc-report.nf
nextflow.config

This PR adds a final step to the pipeline to run the QC generation function from [`scpcaTools`](https://github.com/AlexsLemonade/scpcatools). The process and pipeline are pretty simple, but there were a few changes I made along the way, some for clarity and some for bug fixes and some just because I was inspired and/or delusional
* In testing, I ran into a few outstanding bugs in the pipeline (mostly related to alt experiments) that should now be fixed. (In addition to the bugs in `scpcaTools` itself that were fixed in that repo).
* I altered the container we are using to track the `edge` release for now, so we will always be using the latest scpcaTools as we update things like the QC report. We will want to freeze this to a release when we start processing.
* In a fit of late night …

Add generation of QC report to pipeline

---

bin/filter_sce_rds.R
modules/generate-rds.nf
nextflow.config

Closes #30. This PR adds the ability to pass through an option for the `lower` parameter as part of `DropletUtils::emptyDrops()` which we call inside the `scpcaTools::filter_counts()`. To do this, I chose to add a parameter for lower to our workflow in the config file and then pass that parameter through to the process `filter_sce` rather than hard code the use of `lower=200` within the Rscript that generates the filtered sce. By doing this, we can directly alter this parameter in the config file if we ever need to rather than going into the R script that is run by the workflow and changing it, making it a bit more transparent. 
In doing this, I also had to remove the pipe between the `make_unfiltered_sce` and `filter_sce` processes so that I could pass through both the …

Implement use of lower=200 during generation of filtered sce

---

bin/filter_sce_rds.R
bin/generate_unfiltered_sce.R
modules/generate-rds.nf

Closes #38
This update to the workflow adds gene symbols to the row data of the single cell experiment objects that we generate. I do this first as part of the unfiltered_sce script, using the symbol information from the GTF file that is already a parameter defined in the workflow config file. I read the GTF with `rtracklayer::import()` which is pretty efficient once we restrict to reading only genes (not transcripts, cds, etc.).
The filtering script had to be modified a bit, because we no longer want to remove all row data before recalculating gene statistics. Instead, we are removing only the columns of the rowdata table that `addPerFeatureQCMetrics()`adds, then add them back recalculated. There is a bit of oddness here in that we select from the `DataFrame` as if it were a vector …

Add gene_symbols to SCE objects

---

main.nf
modules/af-rna.nf

Closes #39. Here I'm adding in support for 5' libraries into the workflow and took the same approach that we used and tested in the [alevin-fry workflow in alsf-scpca.](https://github.com/AlexsLemonade/alsf-scpca/blob/main/workflows/alevin-quant/run-alevin-fry.nf)
I believe these changes should be pretty straight forward, but please let me know if there is a better way to approach making the proposed changes in this workflow.

Add support for 5' libraries 

---

main.nf
modules/af-features.nf
modules/af-rna.nf
modules/generate-rds.nf
modules/qc-report.nf
nextflow.config

Here I am incorporating the `scpca_project_id` column into the `meta` passed along with each channel, and using that information to further subdivide the final output. 
In changing the output files, I also split outputs like alevin results & initial rad files (which we will now keep) into a separate `internal` prefix, with the elements that will go to the front end under the `publish` prefix. Some notes:
- This is slightly different from the approach in https://github.com/AlexsLemonade/scpca-nf/pull/28, which created separate `alevin_dir` and `final_output` parameters, and used those for output. 
- In doing this, I also decided to remove the `sample_id` prefix for the internal outputs, as it seemed like for internal things we might not need that level of nesting (which is usually …

Incorporate project info into channels and output

---

bin/filter_sce_rds.R
bin/sce_qc_report.R
modules/qc-report.nf
nextflow.config

In this PR I am adding to the QC process/script to output information at the library level, including some basic statistics that we were thinking might go into the portal front end. 
Closes #34 
Also addresses https://github.com/AlexsLemonade/ScPCA-admin/issues/210
I am attaching here an example of the output csv file, [SCPCL000001_metadata.csv](https://github.com/AlexsLemonade/scpca-nf/files/7228171/SCPCL000001_metadata.csv).
The equivalent json (which is also exported, but gh won't let me attach), appears below.
```
{
"library_id": "SCPCL000001",
"sample_id": "SCPCS000001",
"filtered_cells": 1642,
"unfiltered_cells": 61980,
"total_reads": 121894873,
"mapped_reads": 90729577,
"genome_assembly": "Homo_sapiens.GRCh38.104",
"mapping_index": "Homo_sapiens.GRCh38.104.spliced_intron.txome", …
```

Export cell statistics & other metadata

---

modules/generate-rds.nf
modules/qc-report.nf
nextflow.config

Closes #47 
This updates the tag on the docker image to use v0.1.0 of scpcaTools, freezing that last image in place (for now).
In testing a separate step, I ran into some out of memory errors, so I added another process label with higher memory requirements (but still only one CPU, though I might later reconsider this to bump the CPU a bit too). I also tweaked the nextflow retry settings because those seemed to not be working as expected (i.e. I was clearly getting error 137 but the job was not being retried). With the modifications I made and the test sample I was working with, I still get an OOM error for one of the jobs (filtering), but this then correctly reruns with double the memory.

Use v0.1.0 of scpcaTools & memory/retry tweaks

---

nextflow.config

In running the first set of samples, I noticed that we were using quite a bit less memory during mapping than we were requesting. So here I am making the memory request for those jobs smaller. Now that we have a working retry strategy, this should still work even in the rare event we exceed the lower limit. (This may also allow us to recover from some disk space limits we had run into, as the second run will probably require a larger portion of each instance, leaving more disk space available on shared instances.)
I also here am updating to use cr-like-em for processing, which we said we would do, but didn't actually implement.

Reduce memory requirements & change resolution strategy

---

build-index.nf
nextflow.config

Closes #65. This PR adds the `cellranger_index` process to the workflow for building the indices, `build-index.nf` ensuring that when we build all of our indices they will use the same assembly. I followed the same setup that was previously used in generating the cellranger index in [`alsf-scpca/workflows/rnaseq-ref-index/build-cellranger-index.nf`](https://github.com/AlexsLemonade/alsf-scpca/blob/544673eb008843548ac5c8663da65d4732d1f158/workflows/rnaseq-ref-index/build-cellranger-index.nf). 
This was pretty straight forward and I was able to test it and everything ran successfully, producing a new index with ensembl 104. The only question I had was about how we wanted to name this index. I included the assembly name that we use in the splici index and then appended `_cdna_cellranger`, …

Add process for building cellranger index to build-index.nf

---

modules/af-rna.nf
modules/spaceranger.nf
nextflow.config

In processing the Mullighan samples, there was one sample in particular with FASTQ files totaling 116 GB in size. Previously we had been using the default queue on batch which was not big enough to hold these files and the only way to successfully process this sample (or any other sample with FASTQ files this large) is to use the `bigdisk` queue. 
However, we do not want to use the `bigdisk` queue for all of the samples, so I have added a new label that uses the default queue on the first task attempt and then the `bigdisk` queue on the second task attempt. I have tested this and it works successfully for the Mullighan sample that had issues previously and switches to the `bigdisk` queue on the second attempt. 
Additionally, the `cellranger_index` was left out of the params previously and …

Adjust memory requirements for alevin rad process

---

modules/spaceranger.nf
nextflow.config

Closes #71. Here I am modifying the workflow for quantifying spatial data to publish only the desired output files in the structure that was discussed in https://github.com/AlexsLemonade/scpca-nf/issues/68#issuecomment-998940420. 
Here, the approach that I took was to move the desired files from the output of spaceranger to a new folder that is named by the library ID and then publish only that folder and it's contents, rather than publishing the entirety of the spaceranger output folder. Right now the way I have it set up is to perform both `spaceranger count` and then the file moving within the same process before only publishing the desired files. An alternative approach would be to keep the spaceranger output folder intact (other than removing the bam files) and publishing it to the …

Restructure output files for spatial module

---

bin/generate_spaceranger_metadata.R
modules/spaceranger.nf

Stacked on #72. 
This PR adds another process to the spatial workflow to create a `library_id_metadata.json` for spatial libraries, similar to the `json` file we create for single-cell/single-nuclei libraries. After quantifying the spatial libraries using Spaceranger, the metadata and directory containing the quantified output are passed to a process to generate a `metadata.json` file.  Inside that process, an Rscript to read in the specifics about each library and write them out in `json` format is run. 
In general, this follows a similar format to creating the other `metadata.json `which is done inside the `sce_qc_report.R` script. The main differences are as follows: 
- Here we do not have `RDS` files that contain the output, but only the direct output files from spaceranger. In order …

Add process to export metadata.json for spatial libraries

---

main.nf
modules/af-rna.nf
nextflow.config

Closes #41. This PR, adds in flexibility to the workflow to skip the first step of running `salmon alevin` in cases where the RAD file already exists and a new parameter, `rad_skip` is set to true. 
Here we are specifically only skipping the first step in the `af-rna.nf` module as this is the step that is the most costly in both time and memory. This update will enable us to re-run samples that have already been processed and incorporate changes in the later parts of the workflow, such as the filtering steps, or future changes to the QC report, without having to re-run the mapping step. 
To do this, we first add the paths to the rad directory to the meta object. Then we create two channels within the `map_quant_rna` workflow. The first channel includes libraries that are missing the rad …

Allow for skipping of `salmon alevin` process and proceed directly to alevin-fry quantification

---

main.nf
modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/spaceranger.nf

This PR follows https://github.com/AlexsLemonade/ScPCA-admin/pull/299 to make the changes to the nf workflow to remove explicit dependence on s3.
Closes #78
I think I got everything, and I tested using the libarary info file from https://github.com/AlexsLemonade/ScPCA-admin/pull/299 to make sure there were not immediate errors, using samples from bulk, single cell and spatial to test all parts of the workflow. I did not wait for final success on some (looking at spaceranger), but all types started fine, so I believe that all paths were created as expected.

Remove explicit dependence on S3

---

config/reference_paths.config

Closes #79. Here I'm changing the directories for the `ref_dir` and the `barcode_dir` to be the public S3 bucket, `s3://scpca-references` that contain the necessary index and barcode files for the workflow. These two spots should be the only place that need to be changed, since I kept the remaining structure within the reference directory the same. All of the parameters for the indexes use the `ref_dir` as a variable in their path, so changing that one parameter changes all of them. 
I tested that this works and when running the workflow the updated index locations are shown in the configuration in tower and when looking at the command that was executed. Additionally there were no errors for missing index files and everything completed successfully.

Change index and barcodes paths to public reference bucket 

---

bin/generate_bulk_metadata.R
modules/bulk-salmon.nf

This PR adds a process to the bulk workflow to generate one metadata file containing information about each bulk library that has been processed in that project. This results in one `bulk_quant.tsv` and one matching `bulk_metadata.tsv` where the rows of `bulk_metadata.tsv` contain the library ID's that are present in the columns of `bulk_quant.tsv`. 
To do this, I used the same grouped salmon channel that we group by project ID after performing mapping with salmon. This contains the project ID and all associated directories to salmon outputs for that project. I also am inputting the metadata file that contains the metadata information for each library like seq unit and technology. 
Inside the process I am running an Rscript that reads in the library metadata file and list of salmon …

Add process to generate bulk metadata file for each project 

---

bin/generate_bulk_metadata.R
modules/af-rna.nf
modules/bulk-salmon.nf
nextflow.config

Closes #86. This PR adds the flexibility to skip the salmon mapping step in the bulk workflow, similar to skipping the `salmon alevin` mapping in the alevin-fry workflow. In doing this, I implemented the suggestion in #86 to use a parameter `--repeat_mapping` and set the default value to `false`, meaning that mapping will be skipped by default if the necessary salmon output files are present and will be repeated if using the `--repeat_mapping` flag at the command line. 
I followed a very similar structure to the steps we take to skip mapping in the fry workflow, adding the salmon directory to the metadata and then using `branch` to split the channel based on having or not having the expected output file from salmon. The branch that doesn't have the salmon files done yet are then run …

Skip bulk mapping step

---

build-index.nf
config/profile_awsbatch.config
modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/spaceranger.nf

In preparing #80, I needed to make some tweaks to memory requests, and decided that the easiest way to accomplish that was to split up some of the coupling that we had between cpu and memory in the process labels. This may allow us to make some processing more efficient as well (though we are still subject to whims of batch scheduling to a certain extent), as we can use much less RAM for some processes like alevin-fry quant that don't require much memory, while retaining multiprocessing.
So here I have split the CPU and memory requests, and added extra labels to processes as best I thought made sense. 
I also decreased the increments by which we expand memory requests on the logic that we probably don't need to double on failure, but adding 50% memory might make more sense.
**Important …

Split up CPU and memory labels

---

config/containers.config

Updates to use the latest `scpcaTools`, v0.1.4 which incorporates the new `emptyDrops` error handling. I tested this with the default run ID's and with the run ID that I know fails `emptyDropsCellRanger` and all worked as expected.

Update to scpcaTools:v0.1.4

---

config/profile_awsbatch.config
modules/bulk-salmon.nf

In running the samples for the Murphy project, many of them are between 30-40 GB of FASTQ files for bulk samples (compared to previously accommodating for processing ~6 GB files). A few of the samples were failing the `fastp` process and retrying and taking multiple hours and I noticed an increase in their memory usage of 2-3GB up to 6-8 GB. Because `fastp` is normally a much faster process for most samples, I increased the memory to 8 GB for that process and it appears to be working better for all of the difficult samples I had found. 
I also was having issues where `salmon` was failing even after two tries using 32 GB. Without making too many drastic changes, I just increased the number of tries that were allowed from 2-3 and noticed that this also helped. I am running two more …

Increase memory for bulk workflow

---

config/process_base.config
config/profile_awsbatch.config
nextflow.config

Here I am pulling the `process` directives, including settings for most of the labels we use, out to a separate file, and unnesting them from the `batch` profile.
This allows them to be reused if others add a separate profile (for slurm, say), without having to recreate all of the various levels of cpu and memory requirements. 
I left the disk labels in the AWS config (adding a bit of commentary), as those seem to be more specific to AWS, as what they do is set queues. Other systems may not require modifying disk sizes, and if they do they may specify it differently.
Also added a change from `bucketDir` to `workDir`, which is the only option in the docs. In the other direction, I added a `docker.userEmulation` option, copied from nfcore, for local running. This should solve potential …

Split process settings from AWS profile

---

examples/user_template.config
external-data-instructions.md

Closes #112 
This PR adds more detail about config files and profiles to the external user documentation. 
⚠️ As I was writing, I made some organizational changes to that section and the section about AWS, so this PR should be evaluated before we get too far into revisions, so that those organizational changes don't cause too many conflicts! ⚠️
(I retargeted #120 to this branch, as I think it makes sense to finish this one first.)
The organizational changes are mostly about hierarchy: I moved most everything up a level, but nested the "profile" discussion within the more general configuration discussion. It seemed like talking about workflow parameters in a config file was the easiest transition in, so I did that first, then moved on to the discussion of profiles.
I also moved the two …

Add config file instructions and reorganize a bit

---

external-data-instructions.md

Closes #113
This PR adds the sections about AWS settings. I struggled a bit with how much detail to include, so please let me know if this seems about right, or if there are places where I should include more or less detail. 
I will say that the audience I was aiming for is the one with some experience with AWS, as I don't necessarily want people who have not used it at all to make this their first project. So if it seems somewhat opaque, that might be partly by design, though I tried not to make it _too_scary. I mostly wanted to hit the things that didn't seem obvious to me at first, and the places where we deviated most from the instructions in the Nextflow documentation, which is why the stuff about launch templates and queues is there.
I debated linking to the Terraform files that we …

Add instructions/notes for AWS

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/release-checklist.md
CONTRIBUTING.md
README.md
nextflow.config

This PR adds a few issue templates to the repo, including feature requests and bug reports. Most importantly, it adds a checklist for releases that describes the expected process for creating a new release, following the discussion in #132.
I also changed the `manifest.defaultBranch` to `main` to parallel that change, and added a very brief `CONTRIBUTING.md` document to describe the organization of the repo. We may well want to expand that in the future, but I wanted to at least get a stub in there to describe the branches.  Of course, I am also open to suggestions of improvement now!
Closes #131 
Closes #132

Add issue templates and contributing doc

---

.github/workflows/nextflow-config-check.yaml
README.md
config/containers.config
config/profile_ccdl.config
external-data-instructions.md
nextflow.config

Closes #123
This PR pulls the CCDL-specific settings out to a profile that can be invoked with `nextflow run AlexsLemonade/scpca-nf -profile ccdl` (once this is all merged to main, that is). 
I added default settings for the metadata file and output directory, and updated the docs to reflect that, but I am not sure whether that is better than leaving them blank by default. I welcome feedback on that decision.
I did set the defaults for the 10X containers to be blank, so that we only invoke our containers with the `-profile ccdl` argument.
Are there any other settings that I should move to the `ccdl` profile?
Please also look at the the updates to the documentation that I made to be sure those are clear and understandable. One notable change was to move the warning about who the …

Move ccdl-specific parameters to a profile

---

examples/example_metadata.tsv
external-data-instructions.md
main.nf
modules/spaceranger.nf

Closes #117. 
This PR removes the need to have a separate column in the metadata file with the list of files, specifically for external users using the spaceranger workflow. We had previously been grabbing the sample names needed to run spaceranger from the list of file names, but here we pass the directory through to the `getCRsamples` function, list all the files present in the directory and then grab the sample names that way. In addition, I removed the addition of files to the `unfiltered_runs_ch` in the main workflow, as we no longer need that column for any of the workflow to work. 
I also updated the example metadata to remove that column and updated the external instructions to remove any mention of a `files` column. I did not actually remove the `files` column from our metadata, …

No longer require list of files for spaceranger

---

external-data-instructions.md
main.nf

Okay this PR actually takes the changes from main and merges them into a separate branch off `development` and then is merging those changes into `development`. As expected, here there are only the changes to the spatial workflow and spatial instructions that we would expect. Note that the version in `development` had already been increased to `v0.2.5`. I will close out the previous PR #143.

Actually merge changes from v0.2.5 in main to development

---

modules/spaceranger.nf

In processing the spatial libraries, I noticed that some of the `metadata.json` values had a null value in the slot for the `mapping_index`, which should correspond to the base filename of the index that was used for mapping. Interestingly, this was only a problem for libraries where the spaceranger process had completed successfully once and the process was being skipped upon re-running the entire project, but not on samples where they whole workflow was run from start to finish. This is because we were adding in the name of the index to the metadata in the spaceranger process, so when that process is skipped, it doesn't get added and then that value is null in the metadata. To accommodate for times when we skip spaceranger but still want to re-generate the metadata file, I moved the …

Move addition of cellranger index name to `spaceranger_publish` process to avoid null value when spaceranger is skipped

---

README.md
external-data-instructions.md
modules/spaceranger.nf
nextflow.config

Closes #160. Here I updated the line in the spatial workflow that defines the path to the `metadata.json` file to now output the file to be inside the `SCPCL000000_spatial` directory as discussed in our design meeting. I tested this change and the output folder now looks as expected and the metadata file itself still contains the contents it should have. 
I'm also updating the relevant version numbers here as the next steps after filing this PR is to file a PR to `main` with the same exact changes that are included here and then create a new release so that we can process the spatial project again.

Move spatial metadata.json to be nested inside spatial folder

---

README.md
external-data-instructions.md
modules/spaceranger.nf
nextflow.config

This PR has the exact same changes that were filed in #164 but to the `main` branch in order to prepare `main` for a new release. Once these changes have been incorporated, we can close #160, as the updates to the spatial workflow will be present in both `main` and `development`.

Sync moving metadata file and version number updates to `main`

---

README.md

Closes #156. 
Here I reorganized the main `README.md` file so that we have included a section geared towards outside users looking to process their samples with `scpca-nf`. Following the description in #156 and some feed back in the pilot sessions, I kept the beginning intro section unchanged but had the next header be specific to running outside samples for those outside of CCDL. I then changed the next header to make it clear that that section is specifically for CCDL staff. 
In the section for other users, I added the link to the external instructions and also included a brief outline of the steps that they will need to take with links to the sections that have each of the relevant information. I was back and forth on how much information is too much vs. how much information is helpful …

Reorganize main readme file to include section for external users

---

README.md
external-data-instructions.md

Closes #157. 
Here I updated the external user instructions to include an overview of the entire process for setting up a workflow run and outlining the steps in a bit more detail then was there before. Previously we briefly mentioned the dependencies and then the files that we would need and had a command that people could use to run. 
Based on the issue described in #157 and some discussions in pilots, it seems like it would be beneficial to have the introduction section contain some more detail on the amount of work it takes to actually set up a run and a brief overview of setting things up with links to each section. What I did was create an outline in the overview section of the steps that users would need to take, providing a one sentence description of each step and then links to …

Restructure introduction to external instructions to include an overview of all steps

---

examples/example_metadata.tsv
external-data-instructions.md

Closes #158 and #163. 
Here I am updating the `example_metadata.tsv` file that we provide to mirror the external user instructions and to have run/library/sample ID's that are easier to understand for external users and not of the format `SCPCX`. I started by moving all of the optional fields to be in the second half of the columns so that the first columns are all of the required fields. 
In doing this I made a few changes to the actual columns: 
- I added `scpca_project_id` to the list of required columns. Previously it wasn't listed at all although we had it in the example file. The reasoning for this is because right now the workflow is set up to nest the output by project ID. If a project ID is not present then it will nest the output into a folder with `no project` as the name. I …

Reorganize example metadata

---

config/profile_ccdl.config
external-data-instructions.md
modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/genetic-demux.nf
modules/qc-report.nf
modules/sce-processing.nf
modules/spaceranger.nf
nextflow.config

Closes #154. 
Here the main change I made was to publishing the alevin-fry output files for both the single-cell and CITE-seq alevin fry processes. I utilized the [`enabled` option within Nextflow `publishDir`](https://www.nextflow.io/docs/latest/process.html#publishdir) to only output the files when specified at the command line. I created the parameter  `--publish_fry_outs` (open to new names if anyone has ideas...) and stored it as `false` so that by default we aren't writing out the files. Then if we want to write out the files (or a user wants to write out the files, then you can just use `--publish_fry_outs` at the command line when setting up the run. I tested these changes and it worked as expected, only writing out the files when using `--publish_fry_outs`. 
The other change that …

Make publishing alevin-fry output optional

---

README.md
external-data-instructions.md

Closes #153. This PR removes any remaining areas of both the main readme and then the external instructions that mentioned running the workflow locally. I also added in statements throughout that mentioned the resource requirements to hopefully drive the point home. 
On the main readme page, I updated the instructions for Data Lab staff to only include running with batch, removing the command that runs locally. 
For the external instructions document, I removed any comments that referred to running the workflow locally and added in the resource requirements in a few places. When referring to setting up parameters I also removed the command that showed setting them at the command line as that didn't have a config file or profile there so if people copy and paste that it would run locally. …

Include resource requirements and remove local running instructions

---

README.md
external-data-instructions.md
nextflow.config

This PR preps for the 0.3.0 release and updates the version in the appropriate documents from 0.2.7 to 0.3.0. I am filing this to the `development` branch and then after these changes are merged will create a PR with the changes from `development` to `main` as mentioned in the instructions in #172.

Update version to 0.3.0 to prep for release

---

config/containers.config
config/profile_ccdl.config
nextflow.config

Closes #181. Pretty much does what it says and updates the containers that we are using for alevin-fry and Salmon to include the latest versions, 1.8.0 for Salmon and 0.5.0 for alevin-fry. 
I also included the updates to use the parameters to build the `checkpoints_dir` and `results_dir`.

Update alevin-fry and salmon versions

---

bin/add_demux_sce.R
bin/generate_unfiltered_sce.R
bin/sce_qc_report.R
config/profile_ccdl.config
modules/qc-report.nf
nextflow.config

Closes #175
This PR is primarily about adding a sampling of the demultiplexing results to the `_metadata.json` file. I decided to make teh demultiplexing method an option, rather than having it vary by sample. Currently it uses `vireo` by default, and I don't specify the option in the workflow itself, but it is present in the script. I could add it there if we think it would clarify anything, or as a pointer for sometime in the future when we might reconsider.

Add metadata for multiplex counts to json

---

bin/sce_qc_report.R

I somehow missed this when I was testing the last PR; I must have added this error message at the last minute and missed testing it somehow.
fail if *not* in the list, not in the list.

Fix demux test check

---

README.md

Closes #180. 
Here I added in a section on how to process the example data to prepare the example output we have provided to users. That way if we ever update the workflow again to have a change in directory structure or new files/changes that need to be reflected in the output, then we have the command and information for reference. Specifically, it has what metadata file to use and which run ID in the metadata file corresponds to the example data. I also added a note about where to store the files, creating the zip and then making the file public.

Add instructions for processing example output data 

---

bin/filter_sce_rds.R
config/containers.config

Since the new changes that have been incorporated into `scpcaTools` fix the errors seen in miQC we no longer need to have the try/while loop around adding the miQC results to the filtered sce object here. I've removed it and restored the line back to what it was previously, which was just calling `scpcaTools::add_miQC()`. I tested that the changes in `scpcaTools` were sufficient to catch the miQC error and fix it by using the `edge` tag for `scpcaTools` first and testing the workflow on some of the libraries that were previously failing. I confirmed that they do indeed pass now and complete the workflow. I also updated the tag and am using the tag for what will be the next release of `scpcaTools`.

Remove miQC try/while loop and update scpcaTools version 

---

README.md
bin/sce_qc_report.R
config/containers.config
external-data-instructions.md
nextflow.config

Closes #194. 
Here I changed the name for the argument used when calling `scpcaTools::generate_qc_report()` to reflect the new argument, `library_id`. I tested this and all looked good and produced a QC report as expected for a multiplexed library. 
I also am changing the version of `scpcaTools` that we are using to v0.1.7 and then updating the version for `scpca-nf` to v0.3.2 to prepare for the new release.

Change generate_qc_report argument name and update version numbers

---

README.md
bin/add_demux_sce.R
config/containers.config
external-data-instructions.md
nextflow.config

When running the library that had only one HTO, but was classified as demultiplexing, Seurat was failing to perform demultiplexing. To avoid this, we discussed skipping demultiplexing altogether if there is only one HTO and not reporting sample calls. 
Here I check for the number of cellhash ID's and if that's > 1, then we continue with add the demultiplexing results. We are also making changes in scpcaTools to the QC report to adjust for samples like this (AlexsLemonade/scpcaTools#111). I will wait until that gets merged and I can then test those changes with`scpcaTools::edge` and these changes before wrapping up this PR, so I'm going to keep it in a draft state for now. I did test these changes and things worked successfully, but I would like to test in combination with the changes to …

Skip demultiplexing if only one cellhash ID 

---

nextflow.config

This adds a dummy file name to hopefully fix a bug when a real multiplex pool file is not specified.

Jashapiro default multiplex

---

examples/user_template.config
external-data-instructions.md

Since I could not find any S3 permissions issues on our end when working on #205, we tested a setting to make the access to reference files anonymous. This seemed to work, so I am considering it a solution that we should suggest in the configuration file at least. 
We may want to add a sentence about this to the docs as well, but I have not done that yet.
closes #205

add AWS anonymous access to example config

---

bin/sce_qc_report.R

Closes #222 
Mainly because I was tired of scrolling to look at the metadata file, but also because it looks so much better now, this just changes printing out the metadata file to turn it into pretty format.

Make the metadata.json look pretty

---

bin/post_process_sce.R
config/containers.config
config/profile_ccdl.config
config/reference_paths.config
lib/Utils.groovy
main.nf
modules/af-features.nf
modules/af-rna.nf
modules/bulk-pileup.nf
modules/bulk-salmon.nf
modules/bulk-star.nf
modules/cellsnp.nf
modules/genetic-demux.nf
modules/qc-report.nf
modules/spaceranger.nf
modules/starsolo.nf

The primary change here is to track metadata by writing a json file with the contents of the `meta` object when we write files to a checkpoint. 
I did this primarily by implementing the same system as in the `genetic-demux` workflow, but I moved some of the logic out to a separate file, `lib/Utils.groovy` which is automatically loaded by Nextflow (I can't find the documentation for this behavior, but  it seems to load any groovy files in the lib directory, and `nf-core` relies on it, so I don't expect it to change. The closest to documentation I could find was that there is a `-lib` argument to `nextflow`, which I guess might allow a different library to be loaded (as well? instead?))
A limitation of this approach is that it seems like some of the Nextflow functions and objects are not …

Track metadata in checkpoints

---

config/containers.config
main.nf
modules/cellsnp.nf

After creating the vireo image in https://github.com/AlexsLemonade/alsf-scpca/pull/170, this PR  implements its use in the workflow.
I also changed how the Nextflow version is stored in `meta`, as I found in testing that the previous code was storing it as an object type that was interfering with the `-resume` option. So now it is stored as just a string, which is easier to interpret anyway.
closes #219

Use vireo image

---

bin/filter_sce_rds.R
bin/post_process_sce.R
modules/sce-processing.nf

Closes #232 
Here I altered the `filter_sce_rds.R` script to take the probability compromised cutoff param used for filtering in as an argument rather than passing it through the post process script. This change allows us to use it to directly create the `miQC_pass` column that is present in the SCE that gets written to `_filtered.rds`. As a result of this I also stored the cutoff in the metadata of that object, rather than only in the processed object. 
Then in the post processing script I changed the removal of bad cells to directly use the `miQC_pass` column, if miQC was successful, in combination with the minimum gene cutoff. I believe I addressed everything that was mentioned in the issue, but let me know if I missed something. 
The test run is about halfway done, so I'll wait for …

Pass probability compromised cutoff through filtering script 

---

build-index.nf
examples/user_template.config
external-data-instructions.md
get_refs.py
modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/cellsnp.nf
modules/qc-report.nf
modules/sce-processing.nf
modules/spaceranger.nf

Closes #211
Mostly this is documentation, but I also had to make some changes to the `get_refs.py` to give pulled/cached image files the names Nextflow expects them to have (this is mostly undocumented, so yay). 
Please let me know if these docs make sense. We will get another set of eyes when we deploy to testers.
I think this may also address #213, as I seemed to run into that when testing. I think the issue may have been somehow invalid symbolic links created by publish steps when skipping remapping. To address this, I changed all publish steps to include `mode: 'copy'`. This should prevent any deletion of temp or scratch files from removing results in checkpoints or results.

Add instructions for downloading local reference files

---

bin/post_process_sce.R
examples/user_template.config

A bit of a twofer here. 
One part is updating the references to `ccdl_filter` to scpca, which is a bit more specific, and avoids some branding issues. (see https://github.com/AlexsLemonade/scpca-docs/pull/100/files/b23fbc57a2622d1b9a288b89b73602ee04d7c6eb..8b4bf0723a38e6d527e4485136bf55f557d72ed3#r1024292671)
The other is a small change to talk about cacheDir for singularity, which is a thing that has come up with updates to allow pre-pulling images (I should have fixed this in the last PR but missed it)

change ccdl -> scpca for filtering and update template

---

bin/generate_unfiltered_sce.R
modules/sce-processing.nf
nextflow.config

The changes we added to `scpcaTools::read_alevin` in https://github.com/AlexsLemonade/scpcaTools/pull/144 changed some argument names to remove the `intron_mode` and `which_counts` arguments and replace with one `include_unspliced`. Here I modified the script that generates the unfiltered SCE object and reads in the data to accommodate those changes. I know that `include_unspliced` is set to `TRUE` as the default in the function, but I just put it here to be explicit. I didn't add it as a param to the actual workflow, but we could if others think that's important? 
I also removed the `seq_unit` arg that was being passed into the script because we were using it before to figure out which counts to include spliced vs. unspliced. Now we are including both matrices for all of them so no …

Change arguments to `read_alevin`

---

bin/generate_unfiltered_sce.R
bin/sce_qc_report.R
config/containers.config
modules/qc-report.nf
modules/sce-processing.nf

In testing for the upcoming release of `scpcaTools`, I found a few small errors that needed to be addressed here. 
- Passing the processed SCE object through to the QC report 
- In passing the processed SCE object through, I also added some values to the `metadata.json` that gets produced to reflect filtering and normalization additions. 
- Adding a missing `opt`
- remove extra `--seq_unit` option
I also changed to use the tag for what is about to be the most recent release of `scpcaTools`. I did test it with the new `edge` tag that just built after merging https://github.com/AlexsLemonade/scpcaTools/pull/151 and things looked as expected, even in the QC report.

Small fixes to match updates in scpcaTools

---

modules/af-features.nf
modules/af-rna.nf
nextflow.config

This PR adds scpca-meta.json outputs to a few more outputs, for future-proofing & potential tracing. The additions are to the feature rad & quant output directories and to the alevinfry quant directory. These outputs are only used if `--publish_fry_outs` is specified, so I wasn't thinking about them before, but I think it is useful to have the output files just in case!

Add scpca-meta.json outputs to more publishDirs

---

external-instructions.md

Closes #248 
Here I updated the section on the output files in the external users instructions to include mention of the `_processed.rds` file. There were some remaining mentions of the `publish` directory so I changed that too.
I also re-ran our example data through the current development version of the pipeline to update what the output structure will look like. I created a zip of that output and saved it to the same place we had it previously in `s3://scpca-references/example-data/scpca_out.zip` and made sure that the read access was set to world.

Update output files section to include processed rds

---

bin/filter_sce_rds.R

In investigating #250, we found that the culprit, at least in part, is miQC's `enforce_left_cutoff` option. 
Here I am adding an option to our filtering script to make the default for our workflow to set that option as `FALSE`, and only set it as `TRUE` if the `--enforce_left_cutoff` flag is passed at the command line. 
Note that doing it this way requires no changes to the workflow itself!
⚠️ Requires changes to scpcaTools made in https://github.com/AlexsLemonade/scpcaTools/pull/156
closes #250

Change miQC default filtering

---

.github/ISSUE_TEMPLATE/release-checklist.md
external-instructions.md
internal-instructions.md
nextflow.config

This PR prepares for the next release of `scpca-nf` and ups the version tag to v0.4.0 throughout the docs and config file. We also did some rearranging of docs in this release, so I updated the release checklist to reflect those changes as well.

Update version to v0.4.0

---

bin/post_process_sce.R

In starting to re-process projects through `scpca-nf` v0.4.0, I found one library that failed normalization and caused the workflow to stop. We had not been properly handling errors in `scran::quickCluster` so I made the necessary adjustments here to actually catch if that fails. The reason that it can fail is if there are fewer than 100 cells in a library, because we are using the default for minimum cluster size of 100. We could instead enforce a check for how many cells are in the library, but then we wouldn't catch if it fails for other reasons (although I'm not sure what other reasons it would fail?)
I also wanted to note what the downstream UMAPs look like for a library like this. I'm attaching a copy of the updated report for this particular sample after making the adjustments in …

Handle failures to quickCluster before normalization

---

modules/genetic-demux.nf

Just a small change to remove the extra slash in setting the vireo directory.

Remove extra slash in vireo directory

---

bin/post_process_sce.R

Addresses #260 (closes with the help of https://github.com/AlexsLemonade/scpcaTools/pull/159) 
This just adds a `try` around the UMAP calculation in post processing. I tested these changes locally, but we will need the changes in `scpcaTools` to fully test this. This should get around failures in being able to calculate UMAP and the QC report related bugs will be handled in https://github.com/AlexsLemonade/scpcaTools/pull/159.

Catch errors in UMAP calculation

---

config/containers.config
external-instructions.md
internal-instructions.md
nextflow.config

This PR updates to use the latest `scpcaTools` release, v0.2.1, and makes the necessary adjustments in the docs to the version numbers for the next release of `scpca-nf`. I did test this with the new `scpcaTools` and all looked good.

Update to use scpcaTools v0.2.1 and update version numbers in docs

---

integrate.nf

Stacked on #240 
Here I'm just adding a stub to the first process that's part of the integration workflow being added in #240. In the future we should be sure to include a stub in each of our processes for quick testing.

Add stub to integration workflow

---

bin/merge_sces.R
integrate.nf

Closes #236 
Here I am starting the template for the integration workflow so we can start to build in the individual steps. I focused here on the framework of the nextflow workflow and then once we have established what we want, we can move into building the actual script to merge.
For this workflow I started off with the minimum that we needed to get started. I added a param for integration groups and a param for the integration metadata file. For the integration group for now I set it up to be default of `All`, similar to how we have set up the run IDs in the main workflow. The other parameters that we will need for this workflow, the checkpoints directory, the outputs directory, and the library metadata file are all defined in the main config file so I didn't define them here. 
The …

Initiate the integration workflow

---

bin/integrate_sce.R
bin/merge_sces.R
integrate.nf

Closes #247 and #237 
Here I added a script to be used for integrating a merged SCE object using either `fastMNN` or `harmony`. I tried to keep things pretty simple in terms of options and only have the input, output, and method as required options. I also included the harmony covariates as an option in case we ever do want to be able to incorporate that, we can then add a param to nextflow to do that. 
As far as the actual integration, I used the `scpcaTools::integrate_sces()` function that we have and incorporated the minor adjustment to add in a variable for the highly variable genes (https://github.com/AlexsLemonade/scpcaTools/pull/163). 
The other thing I did here was add a process to integrate using `fastMNN`, and the reason for that was so we could start seeing how this script …

Integrate SCE's using fastMNN

---

bin/train_SingleR.R

Partially addresses #270 
Here I started to add in a step to the `scpca-nf` workflow for building and training the models for the reference datasets to use when classifying cell types with `SingleR`. I am just starting by adding in a script that will take as input the reference data, stored as a `SummarizedExperiment` in a rds file and output a rds file with a list of two models, one containing a model using the `label.fine` and one containing `label.main`. This script will then be executed within a process in the `scpca-nf` workflow for creating the models, where all references for the specified project(s) or samples from a project being processed will go through the training step. 
A few comments on decisions I made here: 
- Right now, and for the forseeable future we are only using the …

Script for building SingleR model

---

modules/af-features.nf

Closes #304 
This PR `cut`s (keeping it interesting, would of course be too boring with 2 `awk`s 😅) out the first 2 columns from feature barcode files to pass into `salmon index`, which does not appreciate >2 columns.  
I also decided to remove the "temporary" file after its usage. These certainly aren't big files that _need_ to be removed, but who knows what kind of features this might take one day so I figured removing the file doesn't hurt.

Cut to 2 barcode columns for salmon

---

config/reference_paths.config
examples/README.md
examples/example_metadata.tsv
external-instructions.md
get_refs.py

Closes #297 
Here I updated the external documentation to account for the new changes to the workflow that require specifying the reference/organism to use on a per sample level. 
- I added a note about the `sample_reference` in the preparation of the metadata section of the external docs. 
- I removed the extra reference params that we no longer use from the config file. 
- I updated the `get_refs.py` to only write out the `ref_rootdir` param to the config file that it creates and remove the `assembly`. 
- The example metadata now contains the `sample_reference` column in both the readme and the actual table. 
I believe that was everything that needed to be updated, but let me know if you think I missed something. This PR is also stacked on #289, as we will wait until everything is …

Document addition of specifying references on a single-sample level

---

build-index.nf
references/ref-metadata.tsv
references/scpca-refs.json

Closes #308 
Here I updated the reference that we use for mouse to use Ensembl 104 instead of 109. I changed the `version` in the tsv file and then re-ran the script to generate the `json` file. 
The final step was actually generating the index using `build-index.nf`. I did run into a few small issues that I had to fix along the way. The first was that the `generate_fasta` process was expecting the `fasta` outputs that were named with the index name and then appended with `.fa.gz` so I added that in. The second was that we were previously using `file("${meta.splici_index}").parent` to specify the publish directory, however whenever we used that it was grabbing the full path from my local directory and outputting the files in the S3 bucket with that organization rather than the correct …

Change mouse index to use ensembl 104

---

modules/af-features.nf

Closes #315 
Here I updated the `af-feature` module to publish the rad directories for feature libraries. I also added the ability to skip mapping for feature libraries similar to how we do it for other mapping steps. I did test this with both skipping mapping and running mapping and it worked as expected. 
Also noting that this is stacked on #316 because of [github actions not working right now](https://www.githubstatus.com/).

Skip feature mapping

---

build-index.nf
main.nf
modules/af-features.nf

Closes #313 
This just removes the call to build celltype refs and to add cell types within the main workflow. These can both still be run independently and we will add them back in after we are confident in adding annotations to the workflow.

Remove cell typing from main workflow

---

modules/bulk-salmon.nf

In testing things for release, I found an extra bracket that needed to be removed.

Fix typo in bulk workflow

---

config/containers.config
external-instructions.md
internal-instructions.md
nextflow.config

Just updating the version numbers throughout and then also making sure `scpcaTools` is using the most recent tagged version.

Update to v0.5.0 and tag scpcaTools

---

bin/filter_sce_rds.R
bin/post_process_sce.R

Closes #294 
This PR adds ADT normalization, which only affects 2 R scripts:
- `filter_sce_rds.R` will now calculate size factors on the filtered SCE object. Size factors must be >0, but we don't really want to check that until we know which cells will make it into the _processed_ SCE object. So, in this script, we just store the size factors for later
- `post_process_sce.R` actually performs the normalization using these size factors, and gives a _warning_ if normalization can't be performed (which occurs when a size factor == 0). By this point, the object has been "fully" filtered so by performing the check here we have the most chance of success!
- Any feedback on the specific warning string? More details?  
This has been tested with one ADT + RNA library (first two runs) and one …

Normalize ADT counts

---

config/process_base.config
config/reference_paths.config
examples/user_template.config
external-instructions.md
main.nf
modules/af-features.nf
modules/af-rna.nf
modules/bulk-pileup.nf
modules/bulk-salmon.nf
modules/bulk-star.nf
modules/cellsnp.nf
modules/qc-report.nf
modules/samtools.nf
modules/sce-processing.nf
modules/spaceranger.nf
modules/starsolo.nf

The goal of the PR is to enable local running of the workflow, including basic checks of workflow logic using stubs.
Closes #290 
Closes #151 (though docs are needed here)
To do this, I added `stub:` blocks to all current processes, with the exception of the cell type classification process, which is not currently in the main workflow.
Unfortunately, adding stubs is insufficient for allowing local running, as the memory and cpu requirements are still used for the stub. So to fix that, I added some very simple functions inspired by nf-core to modify our memory and cpu settings, checking new `params` for the max memory and cpu and returning the lesser of the two values. 
So to run locally, you can now do something like:
```
nextflow main.nf -profile ccdl -stub --max_cpus 2 --max_memory 2.GB …
```

Add CPU & memory checks and stubs

---

bin/filter_sce_rds.R

Closes #330 
This PR adds a quick check for ADT target type values, printing a nice warning if anything is invalid that it will default to `target`. I added a few comments that seemed helpful along the way.

Check ADT type values

---

external-instructions.md

Closes #299 
This PR adds documentation to explain that a third column can optionally be included in the `feature_barcode_file` to specify the ADT "target type," as I've been calling it.
Questions for reviewers..
- Did I miss anywhere else in these docs that need to be updated?
- Is it clear enough that the potential values are `target`, `neg_control`, and `pos_control` or would you suggest rephrasing there?
- Should we also say something like "at this time, positive controls are not considered in the pipeline"?

Update external docs to explain `feature_barcode_file` third column

---

modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/genetic-demux.nf
modules/spaceranger.nf

Closes #302 
This adds a check to all places where we skip mapping for the path of the reference to be the same as what's present in the `scpca-meta.json` file. I added this to the af-rna, af-feature, genetic demux workflow, and spaceranger. I also modified what was in the bulk workflow to look specifically for the index path rather than the assembly name and tx2gene file path. 
The only one that still checks for the reference name is the `af-feature`, since we create the index uniquely for each of those and the path to the index is not written out as part of `scpca-meta.json`.

Check index paths match when skipping mapping for all mapping steps

---

bin/filter_sce_rds.R
bin/post_process_sce.R
modules/sce-processing.nf
templates/qc_report/cite_qc.rmd
templates/qc_report/qc_report.rmd

**Stacked on #345**
This PR updates the workflow to use `adt` as the CITEseq name, not `CITEseq`, which involved a bit of R and a bit of groovy (....gRoovy? sorry.). I decided to change the `feature_type` variable we have floating around in the meta list/dictionary/whatever it technically is called, and this information will just flow forward with updated R option defaults. 
All tested and runs through with final `_filtered.rds` & `_processed.rds` looking as expected!

Rename CITEseq to adt

---

bin/post_process_sce.R
modules/sce-processing.nf
templates/qc_report/cite_qc.rmd
templates/qc_report/qc_report.rmd
templates/qc_report/umap_qc.rmd

Closes #336 
This PR updates the QC report to have a bit more information about CITEseq post-processing. There wasn't much that really needed to be done it seemed in the end? I've done where what I think is the minimum we need (note one `TODO` comment in the `qc_report.rmd` file which is a question for reviewers!), but we could add more details, for example, maybe the number of cells removed based on RNA info vs. ADT info. Any recommendations for other stats to include would be helpful! Tagging a couple people for review to crowd source any other ideas for info to include.
While I was here, I also fixed a couple things..
- The `scpca_filter` column is present in both `_filtered` and `_processed` RDS files, so we remove a bit of wrangling
- I cleaned up a couple spacing around parentheses …

Add CITEseq postprocessing to QC report

---

modules/sce-processing.nf

Closes #359, and does what it says!

Remove `adt_name` argument from `post_process_sce` process

---

external-instructions.md
internal-instructions.md
nextflow.config

Towards #354 
This PR updates version strings in the places it needs to be updated.
Some `grep` confirmation - 
```
» grep -r "v0\.5\.1" .    # no output!
» grep -r "v0\.5\.2" .      
./internal-instructions.md:nextflow run AlexsLemonade/scpca-nf -r v0.5.2 -profile ccdl,batch --project SCPCP000000
./external-instructions.md:This command will pull the `scpca-nf` workflow directly from Github, using the `v0.5.2` version, and run it based on the settings in the configuration file that you have defined.
./external-instructions.md:  -r v0.5.2 \
./external-instructions.md:For example, if you would run `nextflow run AlexsLemonade/scpca-nf -r v0.5.2`, then you will want to set `-r v0.5.2` for `get_refs.py` as well to be sure you have the correct containers.
./nextflow.config:  version = 'v0.5.2' …
```

Update version string in instructions and config

---

bin/train_SingleR.R
build-celltype-ref.nf
config/containers.config
config/profile_ccdl.config
config/reference_paths.config

Closes #380
This PR updates the `build-celltype-ref.nf` workflow to only build a model from the given `params.label_name` (default `label.ont`).  Note at one point I kept getting confused b/w two directory params, so I added some comments into `config/reference_paths.config` for my 🧠 .
I have not yet run this through to update files on `S3`, but I've tested with local output directory and it's working for me fine there!

Only use `label.ont` in SingleR workflow

---

bin/classify_SingleR.R
bin/train_SingleR.R
modules/classify-celltypes.nf
modules/sce-processing.nf
test-celltype-metadata.tsv

**⚠️ Stacked on #380**
Closes #381 
This PR updates the celltype annotation workflow to only expect a single model per flow. Mostly this involved some code simplification and variable renaming for consistency with the current approach.
To run this...
- I made a dummy metadata file `test-celltype-metadata.tsv`, which I've committed here just for testing - it will need to be removed before merge!
- I copied a reference, named as described in ☝️,  that only contains `label.ont` (aka, a single set of labels generated by #380 changes) to `s3://scpca-reference/celltype/singler_models/test-BlueprintEncodeData_model.rds` for use by workflow
I ran as:
```
op run --nextflow run add-celltypes.nf -profile ccdl,batch \
--celltype_refs_metafile /full/path/to/test-celltype-metadata.tsv \  # update your …
```

Use single model for celltype annotation

---

bin/generate_cellassign_refs.R
build-celltype-ref.nf

Closes #384 
This PR builds on the additions from #388 and adds in a process for creating the marker gene x cell type matrices need for `CellAssign`. 
- I created a script that takes as input a marker gene list, a list of organs, and a gtf file and outputs a binary gene x cell type matrix with ensembl ID's. I used the same method as our data integration process to create the matrix. First, I filtered the larger marker gene table by organs and then converted the resulting gene list into a binary matrix.
- I did add options to the script for the columns that contain the cell type and the gene id. In case we ever want to use a different marker table as the reference we could still use this script but change those arguments. The only thing that I don't make optional is the `organs`, because …

Generate marker gene references for CellAssign

---

modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/bulk-star.nf

Closes #392 
This PR updates all of the places we grab fastq files to accept either `_R1_` or `_R1.fastq.gz`. I tested it with one of our samples to make sure that it recognized our files and things worked as expected.

Be more flexible with fastq filenames

---

add-celltypes.nf
bin/classify_cellassign.py
build-celltype-ref.nf
config/reference_paths.config
modules/classify-celltypes.nf

Closes #303 
This PR adds a process for obtaining `CellAssign` predictions to the main cell type annotation workflow. 
- I added this process into the current `classify_celltypes.nf` process where we now get cell type annotations using both `SingleR` and `CellAssign`. Right now for `CellAssign` I only output the predictions and plan to add one more process to merge in the predictions from `CellAssign` to the annotated rds file with `SingleR` annotations. 
- This does rely on the assumption that every project will have both a `SingleR` reference and a `CellAssign` reference. I think that's okay, because I don't see any scenarios as of yet that we wouldn't have them. 
- I used the highest memory and cpu label that we have. During testing, this was immediately failing due to memory errors, …

Add CellAssign predictions to cell type annotation workflow

---

add-celltypes.nf
build-celltype-ref.nf
config/reference_paths.config

Closes #390 
Stacked on #396 
This PR updates the `build-celltype-refs.nf` workflow to use the paths defined in `scpca-refs.json` rather than re-defining them at the top of the script. Originally in #390 I was thinking I would also add a cell type specific json file, but as I worked on it that seemed less helpful. We only have a few parameters that are mostly used to define publish directories and then the other ones are paths to reference files we don't want to store in S3. So in conclusion, I didn't fully make a new cell type specific json file, but instead updated this to remove hard coding paths.

Use reference json file to define paths in building celltype refs

---

bin/cluster_sce.R
main.nf
modules/cluster-sce.nf
modules/sce-processing.nf
nextflow.config

Closes #404 
This PR adds a process to cluster SCEs to the main workflow. This has been successfully tested with `SCPCR000001`. Some notes on this implementation:
- Major caveat about the clustering code _itself_ given some of the discussion going on in #404 - we probably will want to circle back to the exact parameters used, but for now it will do graph-based clustering of some kind at least. (edit - worth noting I don't have `type = "jaccard"` in here, yet?)
- I have ended up using the following variable names, which can be tweaked!
- Clusters are added to `colData(sce)$clusters`
- Two metadata variables are added (this may change depending on the final clustering code): `metadata(sce)$cluster_algorithm` and `metadata(sce)$cluster_nn`. 
- While writing the clustering script, I nearly …

Add process to cluster cells

---

internal-instructions.md

Closes #389 
So I went to document the `references` folder per #389 and was pleasantly surprised that I had already documented the files related to references for the main `scpca-nf`. So I just had to add in some context about the two new files related to building cell type references. 
I added on to the section that I already had in our internal documentation describing the two files. Generally this was pretty straight forward but let me know if I need to expand on anything!

Add documentation for celltype refs files

---

bin/generate_unfiltered_sce.R
bin/sce_to_anndata.R
main.nf

Stacked on #400 
_This is stacked because #400 fails when converting the AnnData objects. An error is thrown because of the type in the `upload_date` column of sample metadata stored in the metadata before conversion._
This PR begins adding the necessary cell-level metadata for CZI compliance to the AnnData objects. I am focusing on adding the columns from the `sample_metadata` and will file a separate PR for adding the library-specific metadata we are missing (tech version and seq unit). 
This is also based on changes made in https://github.com/AlexsLemonade/scpcaTools/pull/217, and until those are merged, and the docker image is up to date, I can't fully test them in the workflow. 
- First, I slightly modified the `sample_metadata` data frame being added to the unfiltered SCE object. I …

Sample metadata to cell-level metadata for AnnData 

---

build-celltype-ref.nf
config/profile_ccdl.config
modules/classify-celltypes.nf
templates/qc_report/celltypes_qc.rmd

Closes #441 
I have tested the celltyping workflow using `label.main` for `SingleR` (including "model training"), and found 2 quick things that needed to be fixed! Everything is working smoothly now, all tested.
- First, this wasn't a bug, but it seemed like the right move. We previously made a parameter called `label_name` for the singler reference label, but this was before we added cellassign. So, I just changed this workflow parameter to be named `singler_label_name` for clarity. I left all R scripts alone.
- Second, this _was_ a bug! The QC report delta median plot x-axis did not the right levels in an ontology-free scenario, so I added levels and now the plot looks as expected.
Report: [qc_report.html.zip](https://github.com/AlexsLemonade/scpca-nf/files/12562576/qc_report.html.zip)

Update SingleR celltyping

---

CONTRIBUTING.md
bin/add_demux_sce.R
bin/classify_SingleR.R
bin/classify_cellassign.R
bin/cluster_sce.R
bin/filter_sce_rds.R
bin/generate_bulk_metadata.R
bin/generate_cellassign_refs.R
bin/generate_spaceranger_metadata.R
bin/generate_unfiltered_sce.R
bin/integrate_sce.R
bin/make_reference_fasta.R
bin/merge_counts_tximport.R
bin/merge_sces.R
bin/post_process_sce.R
bin/predict_cellassign.py
bin/save_singler_refs.R
bin/sce_qc_report.R
bin/sce_to_anndata.R
bin/train_SingleR.R
components/dictionary.txt
get_refs.py
nextflow.config
templates/integration-report.Rmd
templates/qc_report/celltypes_qc.rmd
templates/qc_report/cite_qc.rmd
templates/qc_report/multiplex_qc.rmd
templates/qc_report/qc_report.rmd
templates/qc_report/umap_qc.rmd

There is never a great time to do this, but I thought it was well past time to start using stylers in this repo when we can, and things are _kind of_ quiet at the moment, so I thought I would give it a shot. 
With that intro, here I have added a note to that effect to `CONTRIBUTING.md` and went ahead and restyled all the python, R, and rmd files. There are no code changes here aside from a couple of places where the linter wanted me to change `|` and `&` to `||` and `&&` within `if` statements, which doesn't matter for those cases but is "more correct."
There is no particular style I could find for Nextflow files, so those should be unchanged.

Add style guide & reformat

---

bin/cluster_sce.R
bin/post_process_sce.R

In processing some data for release, I was getting an error for one sample at the `model_gene_var` step in post processing. This was because there was only 1 cell after filtering (yikes!). We account for a low number of cells and failing normalization, but don't account for that in downstream steps. I added a `try` statement around `model_gene_var` up until calculating the UMAP. 
I also updated the clustering script here to account for objects that don't have any PCA or reduced dimensions present.

Account for failed failed model gene variance and pca

---

bin/post_process_sce.R

So that I can finish processing the Collins data, I want to get the changes that handle the errors seen with post-processing added in #449 into `main` and do a point release. This just incorporates the changes in the post-processing script since the clustering script doesn't exist in `main` yet.

Sync error handling for gene variance and PCA to main

---

external-instructions.md
internal-instructions.md
nextflow.config

Should have done this in #455, PR incoming to make the same changes to `development`.

Update version number in config and docs

---

README.md
external-instructions.md

Closes #367 
This PR updates the documentation in this repo to reflect that AnnData objects are now output by the workflow. 
- I updated the main README to note that output is both SCE objects and AnnData. 
- I modified the outputs section in the external instructions to mention that files produced will be both the rds and the hdf5 files. I also updated the expected file output structure and grouped by file type to make things easier to read. 
- I did not include `_adt.hdf5` files in the output structure, but I do mention them in the text. Do we think that's sufficient?
- While working on this I made some changes in the docs to reflect our change to use ADT when talking about CITE-seq.

Document AnnData output

---

bin/generate_unfiltered_sce.R
internal-instructions.md

Closes #369 
This PR makes a few internal documentation updates for how to update example output files. As part of this I updated the current example output link to contain the example output with AnnData. 
- I made sure the example metadata files in `s3://scpca-references/example-data` contained the correct columns and have the correct path to the example files. 
- I ran the `development` branch of the workflow. When doing that I found an error in reading in the sample metadata where we expect columns for both `upload_date` and `participant_id`. Since those are not required columns in the sample metadata (see #467) and we only use them internally, I wrapped the modifications of those columns in `if` statements. After doing that the workflow was able to run successfully. 
- I downloaded …

Include AnnData files in example output

---

bin/generate_unfiltered_sce.R

Related to https://github.com/AlexsLemonade/scpca-docs/pull/154#discussion_r1340154341, we want to keep `participant_id` throughout for consistency. I removed the chunk here that renames `participant_id`.

Remove renaming donor id

---

main.nf
modules/classify-celltypes.nf
modules/sce-processing.nf

Closes #474
I also decided to move the logic of dropping and re-adding the unftilered & filtered sces from the channel into the annotation workflow itself. If we reconsidere whether we want to add annotations to filtered sces, we can do that more easily if the files are already there, and it streamlines `main.nf` a bit to make the flow a bit more clear.

Drop txt and move channel merge logic

---

modules/classify-celltypes.nf

So here is an option to make the inputs to the singler step a bit simpler.
I also simplified the outputs to just the library id and the output directory, because I realized if we do them right the join at the end for the final annotation step could be pretty easy, and I included an example of how that would look.
If we follow that patter, we _could_ actually make the cellassign step fully separate, rather than passing in the outputs from singleR. I don't think it matters much: but it might be a bit simpler and a tiny bit more efficient.
I also commented out the final output chunk because I was getting some odd and intermittent errors there that I couldn't figure out... something about concurrent modifications, but the fact that it was intermittent (though never in CI) was making me crazy.

Simplify inputs and outputs for singler

---

modules/classify-celltypes.nf
modules/cluster-sce.nf
test/stub-celltype-project-metadata.tsv

In my comments on https://github.com/AlexsLemonade/scpca-nf/pull/476, I proposed a bunch of change, and I decided that it would actually be easier for me to just demonstrate and make some of the changes that I was thinking about, so I did that.
The main goal here was to change the output of the singleR process to be a _folder_ with results rather than individual files. This folder also contains the `scpca-meta.json` file. This solves a couple of problems: rather than having to track a bunch of files separately, we just put the output files we want in the folder,  and then pass that along as a single unit. It also gives us a place to put `scpca-meta.json` where we won't be overwriting it or having to give it different names depending on the output. 
For some reason, maybe my bad memory, I …

Use output folder for singler

---

bin/classify_SingleR.R
modules/classify-celltypes.nf

Towards #415 
The next step is running cell assign, done here! I think given all the nice organizational changes in #476 & #477 this is pretty straightforward for review. The one additional thing to note is that I realized we probably need to be including `singler_reference_name` in the same way that we include `cellassign_reference_name`. This wasn't previously needed since we had been doing singler celltyping _and adding to SCE object_ in the same process, where the reference name was accessible from the trained singler model itself. Now that we will be adding singler & cellassign to the final step all at once in the last process, we'll need to grab both reference names for input.
I also have one discussion-y comment to bring up at this point - my memory from our figjam session 🎸  was …

Add CellAssign process

---

build-index.nf
config/process_base.config
main.nf
modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/genetic-demux.nf
modules/spaceranger.nf

With the knowledge gained in https://github.com/AlexsLemonade/scpca-nf/pull/487, I decided it wouldn't be a bad idea to go through this repo and make sure that all variables declared in a function or `.map{}` statement was defined only in that scope using `def`.
The ones here were not causing problems that we know of, but it seems like a good idea, partly as a bit of reminder that those `def` statements actually do something (keep scope local).
The most common changes are in the definitions of paths for step-skipping, where I now make an explicit copy of the input  object and then modify the copy.

Def all internal variable

---

main.nf
modules/qc-report.nf
nextflow.config
templates/qc_report/celltypes_qc.rmd
templates/qc_report/main_qc_report.rmd

Closes #494 
Stacked on #503 
Here I'm adding in the flag to specify whether or not we want to run the cell typing part of the workflow with `--perform_celltyping`. As we discussed, this is set to `false` by default. This means to annotate cell types when running the workflow, you need to use the flag. 
There wasn't really anything too involved here since the output of `annotate_celltypes` already matches the output of `cluster_sce`. 
I tested this with the stub workflow both with and without `--perform_celltyping` and the expected processes were skipped when the flag was absent. I'm doing a test run with an actual library just to be sure everything is good. 
Edit: The tests finished so flag works as expected!

Add perform_celltyping parameter

---

bin/add_celltypes_to_sce.R
bin/classify_SingleR.R
config/containers.config
modules/classify-celltypes.nf
nextflow.config

Closes #446 
This PR adds a new parameter to the workflow, `--repeat_celltyping`, that acts in a similar fashion to `--repeat_mapping`. 
- The default is set to `false`. This means that if the results from either `SingleR` or `CellAssign` already exist in the `checkpoints` folder for a specific library, then those processes will be skipped. 
- If you use the `--repeat_celltyping` option, then regardless of whether the results exist or not, they will be repeated. 
- This argument is only relevant if you are using `--perform_celltyping`, otherwise, cell typing will be skipped for all samples anyway. 
- I kept in the check for the missing reference, so if there's no reference, cell typing is still skipped as it was previously. 
A few other things: 
- I found a discrepancy between the …

Parameter for skipping cell typing if results already exist

---

templates/qc_report/celltypes_supplemental_report.rmd

Closes #517 
This PR updates the delta median section of the cell type QC report and hits all the bullets in #517. I think the diamonds look fine in the plot; the only spots where they are a little weird is for cell types with only ONE cell, but I think that just kind of is what it is no matter what! 
Any viz or textual feedback welcome! 
EDIT: A rendered report!
[celltypes_supplemental_report.html.zip](https://github.com/AlexsLemonade/scpca-nf/files/13032621/celltypes_supplemental_report.html.zip)

Update delta median section

---

bin/add_celltypes_to_sce.R
bin/classify_SingleR.R

Based on https://github.com/AlexsLemonade/scpca-docs/pull/166#discussion_r1367258141, this PR adds back in tracking the reference label type for SingleR. When building the SingleR model se specify the label type to use. That label type is then stored in the metadata of the model object (see https://github.com/AlexsLemonade/scpca-nf/blob/934df294bbfe2a01d8ffdb94ba9f5d6b432a547d/bin/train_SingleR.R#L134).
So here I take the label name that's stored in the reference model object and store it in the results object in `classify_SingleR.R`. Then in `add_celltypes_to_sce.R`, I get the label type from the results object and add it to the metadata of the annotated SCE object. I also used it to check whether or not to map the annotations to the ontology label.

Add label type for SingleR refs to annotated SCE 

---

templates/qc_report/celltypes_qc.rmd

Closes #511 
This PR does some reorganization of the introduction for the cell type section that's in the main report. 
- I simplified a lot of the eval statements to have the same intro regardless of what methods were used. Then I just check for each individual cell type being present before printing out the bullet point for that method. 
- I added in the refs for SingleR and CellAssign. 
- The order is now submitter, SingleR, CellAssign

Update introduction of main cell type report

---

modules/classify-celltypes.nf

When running through some samples and performing cell typing, I noticed that we were still publishing the `_annotated_processed.rds` file to the results directory. 
We don't want to do that and only want to publish the final SCE objects in the process that creates the QC report.

Remove extra publish step

---

templates/qc_report/celltypes_supplemental_report.rmd

Towards #516 
**Stacked on #520**
This PR _starts_ the process of updating heatmaps. Here, I made two broad changes 
- Moved heatmaps above diagnostic section
- Wrote code for calculating jaccard similarity matrices
I did not yet _remove_ any of the current heatmap code. Everything in the heatmap section that comes after the sentence I added `"Note that the remaining heatmap code is going to be updated next!"` is the same as it was before. The two chunks in the heatmap section that come _before_ that sentence are focus to look during review.
I wrote two functions which, together, are calculating jaccard similarity between two categorical columns, e.g. cluster & singler annotations. The function `calculate_jaccard_similarity()` does the actual calculation for a given jaccard similarity …

Add jaccard calculation code

---

bin/add_celltypes_to_sce.R
templates/qc_report/celltypes_qc.rmd
templates/qc_report/main_qc_report.rmd
templates/qc_report/utils/celltype_functions.rmd

Closes #512 
Closes #527 
This PR makes the necessary adjustments to fix some of the formatting and display of the tables that are mentioned in #512. 
- In the `create_celltype_df` function, I added a check for submitter cell types and set NA to "Unclassified cell". 
- I also made sure to add in the re-leveling so that the table for submitter cell types is in order of percentage of cells with "Unclassified cell" last. 
- I also fixed a small typo that meant we weren't setting the cell ontology labels as the annotations, which is what we want to do. That should now fix the situation of seeing the cell ontology ids as the axis labels in the plots. 
- The last thing I did was just add a check that all submitter cell types are not NA. If that's the case, then `has_submitter` is set to …

Fixes to cell type tables

---

bin/cluster_sce.R
templates/qc_report/celltypes_qc.rmd

Closes #513 
Stacked on #528 
This PR makes the small adjustments to the UMAPs that were outlined in #513. 
- I made sure that the methods for clustering and weighting were capitalized. One thing to note is that we are grabbing these from the metadata of the processed object. Should we store them in the object as capitalized instead of what I did here? 
- I moved the description of the cell type UMAPs to be immediately before the first cell type UMAP rather than grouped with the description of the cluster UMAP. 
- Part of the fixes in #528 actually helped account for all the NA's being renamed and counted when grouping the cell types together. 
- I updated the name of the "other cell types" group to "All remaining cell types" and updated the text accordingly.

Fix UMAPs in main cell type section of report

---

bin/add_celltypes_to_sce.R
bin/classify_SingleR.R

In working on processing some projects through CellAssign, I was running into an error when adding the cell types to the SCE object. 
I went back and realized that we weren't properly storing the name of the reference label in the SingleR results file. Also, we didn't pass on the `cell_ontology_df` from the model to the results. We need that to map cell ontology IDs. 
One other thing to note is that I had to separate out modifying the `colData` and replacing the `colData`. Nextflow was complaining about the `colData` function.

Save singleR reference label and ontology data frame to singleR results

---

external-instructions.md
internal-instructions.md
nextflow.config

Since we recently fixed an error with processing samples without cell types from submitters (see https://github.com/AlexsLemonade/scpca-nf/pull/524), we need to tag a new release. This just updates the tag to v0.6.1 throughout.

Update tag to v0.6.1

---

components/dictionary.txt
templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd

Towards #516 
This PR takes the next steps in updating heatmaps:
Edit - the report! 
[celltypes_supplemental_report.html.zip](https://github.com/AlexsLemonade/scpca-nf/files/13207665/celltypes_supplemental_report.html.zip)
- Heatmaps now come first 
- note that the introductory parts are still forthcoming - #514 & #515
- I removed the previous function we had been using for making heatmaps. For now, I've commented out the code that used that function to compare singler/cellassign to submitter. The next PR will clear this out using the strategy we land on in this PR.
- Heatmap styling changes:
- I have updated the color scheme to something less dramatic - a standard yellow and red, but this can certainly change!! (it's super yellow now which is partly b/c these clusters + submitter …

Establish updated heatmap styling

---

templates/qc_report/celltypes_supplemental_report.rmd

Ever towards #516 
More heatmaps, and please enjoy the branch name, and if you don't enjoy the branch name, it means you still need to see _Zoolander_.
1. Heatmap function has been implemented
2. Although I use the heatmap function for the first two heatmaps, I don't for the third (directly comparing singler-cellassign) since it is not a list of stacked heatmaps.
- If we want, I can create a 2nd function to just make a heatmap from 1 matrix and call it from the current function. This would modularize the code further; let me know if we want to see this happen! I didn't do it (yet?) since this heatmap seemed sufficiently different that it might be fine to not use the function.
3. I realized that I have been developing this with unrealistic submitter labels - they have just been single …

Add remaining heatmaps

---

bin/sce_to_anndata.R
main.nf

When running the multiplexed project through the workflow, I noticed that one of the libraries was still getting converted to AnnData, even though it has a cell hashing library. This then threw an error in the actual conversion process which we want to avoid. This library was still around because even though it has a cell hashing library, it's not actually multiple samples, so it doesn't get categorized as a `multiplex_libs`. So then it's not filtered out. 
Here, I created a separate list of all libraries that have cell hashing even if they aren't multiplexed. I then use that to filter before converting to AnnData. I tested this with the problem library and AnnData conversion was successfully skipped.

Make sure that AnnData conversion is skipped for any library with cell hashing

---

external-instructions.md
internal-instructions.md
nextflow.config

Related to #543, this just updates the version numbers in the docs to be `v0.6.2`.

Update version to v0.6.2

---

bin/sce_to_anndata.R
templates/qc_report/qc_report.rmd

This PR catches a few errors/issues that were in the AnnData release. 
1. Apparently I was using `nrows` instead of `nrow` for checking the number of genes/ features in the `altExp` before exporting to AnnData. R did not like that. 
2. I removed the chunk that reads in the cell type section to the qc report. 
Here's a copy of a report for a library that I tested that has submitter cell types. No more cell type section for now. 
[SCPCL000495_qc.html.zip](https://github.com/AlexsLemonade/scpca-nf/files/13298997/SCPCL000495_qc.html.zip)

Remove cell type section and fix altExp export to AnnData

---

bin/cluster_sce.R
bin/post_process_sce.R
internal-instructions.md
modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/cluster-sce.nf
modules/export-anndata.nf
modules/sce-processing.nf

Closes #480
Closes #505
Here I am changing inputs and outputs for a few different processes to make them different files and/or directories. 
In some cases this was accomplished by modifying the underlying scripts to write out new files rather than overwriting the inputs, which seems safer anyway.
In `fry-quant` processes, I modified the `alevin-fry` steps to copy over relevant `alevin` files into the new directory (keeping the input rad directory separate), rather than deleting `.rad` and `.bin` files.
The other big change is that in `modules/export-anndata.nf` I combined the moving of `logcounts` into the same process as the original anndata export, which saves any renaming and simplifies the workflow a bit (no `mix` needed, and no double-publishing of files). We had originally kept …

Adjust processes to not modify inputs

---

.pre-commit-config.yaml

Does what it says! 
Set to only update existing TOCs.
Inspired by https://github.com/AlexsLemonade/scpca-nf/pull/502#discussion_r1391789864

Add doctoc to pre-commit

---

bin/add_celltypes_to_sce.R

Mentioned in https://github.com/AlexsLemonade/scpca-docs/pull/193, we had both `ref` and `reference` in the names for items in the metadata of the final SCE object. This just changes everything to `reference`. Let me know if I missed any spots!

Standardize how we store cell type reference information

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd

Closes #542 
Closes #549 
This PR updates text in the QC report, as discussed in #542. I also updated the `CellAssign` reference parsing.
The only change that was mentioned in the issue but _not made_ here was adding a sentence to the `SingleR` section to mirror the `CellAssign` section with - first singler calculates a score for every label at every cell. I struggled with phrasing that wasn't both repetitive and overly-wordy, so I left it as it. If you want to take a stab at something here, go for it! 
I also deleted `red` and didn't include `blue` - eh?

QC text updates

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd

Closes #519 
As discussed*, I've added heatmap alerts - `warning` for the top of the celltype report, and `info` for the other spots. 
*Slight wording tweak but very happy to backtrack to the original suggestion in Slack for the UMAP text! I went ahead and added "confounded" in there, which is a concept I like to emphasize, but it might be getting too much in the weeds. Please suggest rephrasing wherever you see fit!
I also got changed all the `heatmap_height`s to also be `plot_height`, for simplicity, while I was here. No need for 2 unused variable definitions when we could just have the 1, I figured.
Here are screenshots of the relevant rendered parts!
-----------------------
-----------------------
------------------------

Add multiplex warnings to QC report

---

modules/classify-celltypes.nf

Somewhere along the line a semicolon was lost. The wayward semicolon was sad, shivering in the dark, but now it has been found and returned to its rightful home on line 151, near its semicolon friends. 
This did not affect any code, but seemed worth fixing.

Add missing semicolon

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/umap_qc.rmd

This PR addresses some QC report things identified in #469 we'd like to fix.
- Use `theme(aspect.ratio = 1)` instead of `coord_fixed()` for UMAPs
- Bigger width for diagnostic cell type plots
- Ensure heatmaps are at least 4" tall (related to #541)
- Bonus, fix a bug introduced in https://github.com/AlexsLemonade/scpca-nf/pull/574/files
- We moved some text into an `as_is` chunk with `glue::glue()`, so need to use `{}` for variables, not \``r stuff`\`

Update plot dimensions

---

examples/README.md
external-instructions.md

Closes #570 
Two changes:
- In `external_instructions.md`, I added some bullets to actually describe what goes into the TSV files. But, do we want to link out to third party format, and if so where specifically to link out to? Is all the wording ok as is, too?
- In `examples/README.md`, I tell readers to go look at those file descriptions. Is this info in an ok place?

Update example file docs

---

references/celltype-reference-metadata.tsv

Closes #416 
This PR adds additional references to use with `CellAssign`, using the organs available in the PanglaoDB marker gene list. 
- I included all references we may need to run each project (see https://github.com/AlexsLemonade/ScPCA-admin/pull/713). This includes two references that combine organs: 
- `adrenal-reproductive-compartment`, which includes the adrenal gland, pancreas, and reproductive tissue to account for the project that contains both Adrenal corticocarcinoma and a germ cell tumor. 
- `bone-and-soft-tissue-compartment`, which includes bone, smooth muscle, and connective tissue to account for the projects that contain samples that come from various bone and soft tissue areas in the body. 
- I also added some extra references for various organs that we might want to …

Add new references for cell type annotation

---

references/celltype-reference-metadata.tsv

I went to build the references following #587 and realized I spelled embryo wrong in one of the lists.

Spelling fix in ref metadata

---

bin/add_celltypes_to_sce.R
templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/utils/celltype_functions.rmd

Closes #591 
Based on discussion in #591, we decided to handle any potential mismatches in barcodes between the processed object and the existing `CellAssign` or `SingleR` results by labeling any cells not present in the results as `Unclassified cells`. This PR makes that adjustment and fixes some other smaller errors I discovered during test runs. 
- I accounted for potential fails in `density()` following the suggestion in https://github.com/AlexsLemonade/scpca-nf/issues/591#issuecomment-1823531553. 
- All of the missing cells have been annotated as `Unclassified cells` in the processed SCE object. This avoids any cells being labeled as `NA` accidentally. This happens as part of `add_celltypes_to_sce.R`. 
- In the QC report, I check for any missing cells and output a warning that some …

Account for mismatches between old cell typing results and current processed object and handle missing UMAPs

---

external-instructions.md
internal-instructions.md
nextflow.config

With the additions in #596, we now have a workflow that is working as expected and we are ready for release. This PR just updates the version tags to be `v0.7.0`.

Update versions to 0.7.0 in docs

---

merge.nf

Closes #593 
This PR completes the steps needed to repurpose the integration workflow to be for merging. 
- I removed the parameters for the`merge_metafile` and the `merge_group`. I also removed the part of the workflow that reads in the `merge_metafile` and joins it with the `run_metafile`. 
- Instead, we want to merge all libraries by project. I required the `project` parameter to be provided and filter the `run_metafile` to only contain libraries in the specified project. 
- Before merging, I group by the project ID so that each merged object contains all libraries for a given project. 
These changes were pretty straightforward, but I haven't had a chance to test them yet. I'm using all the resources to run CellAssign, so I'll request a review once I have the chance to test this.

Repurpose integration workflow to be specifically for merging

---

bin/merge_sces.R
merge.nf

Closes #595 
This PR accounts for libraries that have feature data before merging. Specifically, any libraries that have ADT/CITE-seq data will retain the `altExp` in the object, while any libraries with cell hashing will not include the `altExp` in the merged object. I made the following changes: 
- To the script for merging SCE's, I added an option to `--include_alt_exp`. This mirrors the argument being added in https://github.com/AlexsLemonade/scpcaTools/pull/243, but here I am setting the default to be false. So by default the `altExp` will not be included unless the data specifically has CITE-seq/adt data. 
- I create a list of all project ids that have at least one library with CITE-seq data. For each project being processed, I created a `has_adt` value that gets passed to the …

Account for feature data when merging objects

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd

Closes #611 
Closes #612 
In evaluating some of the reports from running cell typing, I noticed that it was hard to discern which cell belonged to which cell type because of the colors we were using. I tried some other color palettes, including `Okabe-Ito`, and it improved the colors, but there are definitely still some issues with discerning cells in the plot. After talking through this with Stephanie on Slack, we decided to try a different approach and make a panel of UMAPs. Here, each UMAP shows the cell type of interest in red and all other cells in grey. We are still limiting it to only show the top cell types, but I actually think this is a lot more clear and easier to distinguish cells. To accomplish this I did the following: 
- I created a new function for producing each of the …

Create faceted UMAPs by cell type

---

templates/qc_report/celltypes_supplemental_report.rmd

Here I just added a label for the y-axis for the CellAssign plot to mirror what we have in the SingleR delta median plot.

Add y axis label for CellAssign probability plot

---

bin/merge_sces.R
config/containers.config
merge.nf

Closes #604 
⚠️ Stacked on #610 (Because this is slightly dependent on decisions made in #610, I'm going to wait to request review)
This PR adds a process to convert the merged SCE objects to an AnnData object. When converting to AnnData, I chose to use the same scripts that we use in the main workflow to convert the object and then move the counts. The reason for this is I think it's probably best to be consistent in how we format our objects. In particular, with the AnnData objects, we add the sample metadata as columns in the `colData` and do a little bit of renaming. I don't think there's any reason we shouldn't be doing that here. 
This process doesn't differ much from the conversion process in the main workflow, except here, we know that the only time we will have an altExp is if …

Add process for converting merged objects to AnnData

---

bin/move_counts_anndata.py
bin/sce_to_anndata.R
merge.nf
modules/export-anndata.nf

Closes #616 
This PR adds a new flag, `--compress_output` to the script for converting objects from SCE to AnnData. This means that by default we set compression to `none`, unless the flag is used. This allows us to specify compressing only for files that are not processed. 
For zipping the processed files, I added the argument to the `object.writeH5AD()` function. 
I did not change the extension of the HDF5 files here, because that change doesn't just affect us. I think if we want to do that we should do that separately. 
I tested both the main and merging workflow to be sure that the new additions work.

Compress AnnData output

---

config/profile_awsbatch_auto.config

Closes #623 
Here I updated the `batch` profile to use `maxSpotsAttempts = 2`, instead of the default of 5. 
I also udpated the `queue` so that for the first two tries we use the auto scale queue we have been using, but for the third retry we use an On Demand queue. 
I think we might want to actually test this with a few libraries before we merge this in? 
Also, I'm merging this into main so that we can release this along with any CPU changes that may happen before processing the projects through CellAssign again.

Update batch profile to set max aws retries and On Demand queue

---

config/process_base.config
config/profile_ccdl.config
modules/classify-celltypes.nf

Based on what we found in #622, we want to use 96 GB and 12 cpus for classifying with CellAssign. This PR adds a new label for 96, removing the old 128 GB label. And then updates the process to use the desired resources.

Update CPU and mem requests for CellAssign

---

modules/qc-report.nf

I noticed that we show the filename of the cell type report in the [screenshots](https://github.com/AlexsLemonade/scpca-docs/blob/sjspielman/celltype-release/docs/images/sample-download-folder.png) and in the[ download section of the docs](https://github.com/AlexsLemonade/scpca-docs/blob/sjspielman/celltype-release/docs/download_files.md) and it doesn't match up with the filename that we are using here. 
I updated the output file to be `SCPCL000000_cell_type_report.html` to be consistent with how we named it in the docs.

Make sure cell type report file name matches the docs

---

templates/qc_report/celltypes_qc.rmd

Closes #637 
This PR cleans up legend placement and makes associated changes for the faceted UMAPs where we highlight 1 cell type in each facet. Here's an overview of the changes:
- I modified the lumping function to also wrap labels to 35 characters, which seems to be about right for the legend "slot" and associated spacing changes I made
- Note that for the wrapping, I wrote a separate `mutate()` altogether since I think that's a bit more legible. 
- One wrinkle for wrapping is that, when there are two lines of text in the facet strip label, it slightly change the aspect ratio so it's not quite equal to 1. I don't think this a big deal though? 
- I fixed factor ordering - After running `fct_lump()`, we lost our original factor order and levels became alphabetical. Now, we are back to …

Update UMAP faceting code

---

main.nf
modules/af-features.nf
modules/af-rna.nf
modules/bulk-pileup.nf
modules/bulk-salmon.nf
modules/bulk-star.nf
modules/classify-celltypes.nf
modules/genetic-demux.nf
modules/sce-processing.nf

Closes #639
This PR adds a whole bunch of checks for files existing, including the original scope of #639 and more spots that _seemed_ like they could use it.
I changed the `has_rad` and `make_rad` order since that made more sense in my brain. Here's how I set it up in `af-rna.nf`:
- We set up to run mapping when (in order) the following are met. Otherwise we do not run mapping.
- mapping is requested
- there is no rad directory
- the assembly has changed.
- If we _are_ mapping:
- If fastq do not exist, then this will error out on lines 141-142
- If we are _not_ mapping:
- There needs to be a rad directory that already exists. If it doesn't exist, then this will error out on line 151.
The one item I'm not sure I fully covered is ensuring the rad directory gets created if we are running …

Fail for missing mapping files, and other missing files

---

bin/merge_sces.R

Closes #655 
Now in the correct repo! This PR updated `merge_sces.R` to handle cell type columns better:
- Find all the cell types that are present in _any_ SCE
- Define a baseline (taken from `scpcaTools` default) set of columns to keep as `retain_coldata_columns`
- For each cell type that is present in at least 1 SCE, add the relevant cell type columns into `retain_coldata_columns`
- For SingleR, I only add `singler_celltype_ontology` if ontology labels were used for at least one library 
- Finally, tell `merge_sce_list` about the `retain_coldata_columns` vector
Moreover, here's how I handle libraries without the given cell type method, but where that method exists in other project libraries:
- Submitter
- Add the column `submitter_celltype_annotation` with the value …

Keep cell type columns when merging

---

bin/merge_sces.R

This PR is related to this comment https://github.com/AlexsLemonade/scpca-docs/pull/237#discussion_r1457593604:
> And found something else we need to fix! Looks like merged objects are missing `scpca_filter` and `adt_scpca_filter` (if at least 1 library has cite). I feel pretty sure we want to keep those columns around! I'll file a PR in `scpca-nf` to retain those columns.
Here is that PR! Script runs locally ✅

Retain filter columns when merging

---

bin/merge_sces.R

Another merging fix, as the PR title says! Currently we have objects as - 
```
> rowData(sce)
DataFrame with 60319 rows and 10 columns
SCPCL000001-gene_ids gene_symbol SCPCL000001-mean
<character> <character>        <numeric>
ENSG00000223972      ENSG00000223972     DDX11L1       0.00247619
ENSG00000243485      ENSG00000243485 MIR1302-2HG       0.00225397
ENSG00000284332      ENSG00000284332   MIR1302-2       0.00000000
ENSG00000268020      ENSG00000268020      OR4G4P       0.00000000
ENSG00000240361      ENSG00000240361     OR4G11P       0.00000000
...                              ...         ...              ...
ENSG00000225491      ENSG00000225491   UBE2Q2P4Y      0.002476190
ENSG00000185894      ENSG00000185894       BPY2C      0.000000000
ENSG00000228296      ENSG00000228296 …
```

Don't rename rowdata `gene_ids` column

---

merge.nf

This PR fixes a silly 🐛 in `merge.nf` where checking the project was adt or multiplex was not working correctly, because of nextflow syntax. This bug was discovered b/c a CITE-seq project's merged object contained no `adt` altExp. Turns out the code told the process that merges SCEs that there was no adt, so at least the subsequent logic works well!
It's running now with the fix, but should work. Here's what the incoming channel to the merge process now looks like. Note that the second item is `true`, correctly reflecting that it _has ADT_.
```
[SCPCP000003, true, false, [SCPCL000050, SCPCL000051, SCPCL000074, SCPCL000697, SCPCL000698, SCPCL000700, SCPCL000702, SCPCL000705, SCPCL000706, SCPCL000713], [/nextflow-ccdl-results/scpca/processed/results/SCPCP000003/SCPCS000053/SCPCL000050_proces …
```

Fix merge.nf workflow adt and multiplex check

---

bin/add_celltypes_to_sce.R
bin/predict_cellassign.py

So I went to run the next set of projects and pretty quickly `CellAssign` failed for `SCPCL000784`. I did some digging and this processed object only has 6 cells, which seems to be part of the reason it's failing. I think with so few cells, the default values that define the training set don't work. After doing some googling of the errors that I was seeing (which were slightly different locally vs. on Nextflow), I saw a lot of mention of the default training size not working with fewer items. So I went through the [CellAssign docs](https://docs.scvi-tools.org/en/stable/api/reference/scvi.external.CellAssign.html#scvi.external.CellAssign.train), and noticed that if I set the `train_size` to be smaller, then it worked. With 6 cells, `train_size=0.6` does not work, but `train_size=0.5` does …

Deal with small numbers of cells and CellAssign

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/utils/celltype_functions.rmd

When working on a plot for the paper, I noticed that we don't remove the `Unclassified cells` from the heatmaps, even though we have a nice little blue box that says we do.

Actually remove unclassified cells from heatmap

---

bin/sce_to_anndata.R

When running the multiplexed samples through the workflow, I was getting the following error: 
```
Command error:
Warning message:
replacing previous import ‘S4Arrays::makeNindexFromArrayViewport’ by ‘DelayedArray::makeNindexFromArrayViewport’ when loading ‘SummarizedExperiment’ 
Error in scpcaTools::metadata_to_coldata(sce, join_columns = "library_id") : 
The specified `join_columns` are producing multiple matches, but only one match is allowed.
Calls: format_czi -> <Anonymous>
Execution halted
```
This is because we are using the `sce_to_anndata.R` script to convert all objects to AnnData prior to running `CellAssign`. In a separate process, we use this same script to do the conversion to produce the final AnnData output. However, in that process, we are skipping any multiplexed samples …

Skip sample metadata addition to colData if cellhash is present

---

bin/generate_unfiltered_sce.R
templates/qc_report/celltypes_qc.rmd
templates/qc_report/main_qc_report.rmd

Closes #645 
This PR makes a couple changes:
1) In `generate_unfiltered_sce.R`, I added a new `metadata` field for `sample_type`. Note that I opened https://github.com/AlexsLemonade/scpca-docs/issues/252 for docs followup. I also learned about `tibble::deframe()` along the way, and I enjoyed that.
2) In `main_qc_report.rmd`, I added a chunk to print a 🟦 stating if we have a pdx or cell line, and if the latter there are no cell types. See attached screenshots for how this looks - how do we feel about placement? Should I move this into the section `Processing Information for library SCPCL`?  (edit - after filing this, i saw and fixed the `if` typo in the cell line blue box) 
3) Fix the new `forcats::fct_drop()` code.... this function operates on characters, not dfs.... Booooo.
----

Add sample type to metadata and associated QC box

---

bin/add_celltypes_to_sce.R

In running through a multiplexed library to completion, there was a lingering error in `add_celltypes_to_sce.R` where we were checking that the column names were equal to `barcode`. That works when we only have one column, but when we have multiple, it checks each column name against `barcode` and returns a vector. R doesn't like that there are multiple TRUE/FALSE values as a vector, so I added the `all` statement here. If the only column names are `barcode` then we assign cells to `Not run`, otherwise we proceed with adding in celltypes. 
Note that I did run this and everything ran to completion. I think we are good to do another release with these new bug fixes?

Check that all column names are "barcode" 

---

modules/af-features.nf
modules/af-rna.nf

Closes #670 
This PR fixes a bug to ensure that `it.file_directory` is not `false` in the first place before we check if it exists. Workflow now runs without the associated error.

Fix missing files directory bug

---

bin/generate_unfiltered_sce.R
bin/merge_sces.R
merge.nf
modules/sce-processing.nf
templates/merge-report.rmd

Closes #661 
I am opening this PR as a draft, since we are still working to finalize the `scpcaTools::merge_sce_list()` function updates https://github.com/AlexsLemonade/scpcaTools/pull/261 which this depends on. But, I have locally run the code with the current version of `merge_sce_list()` and it is working. If anyone wants to have a look at the code before I actually mark this ready for review, feel free!
First, I determine all modalities which are present. Then, handle columns which need to be included for each of `"adt"` and `"cellhash"`, if present. It also occurred to me that we should maybe keep the cellhash _stats_ columns, even though we aren't keeping the cellhash altExp itself (any disagreement?). We don't need to be explicit about those columns for `"adt"`, since …

Update colData merging based on altExps 😈 

---

bin/merge_sces.R
templates/qc_report/main_qc_report.rmd

**Stacked on #666 😈**
Closes #676 
This PR updates the logic where we print the `metadata(sce)$sample_type` info box at the top of the QC report. I'm filing as a Draft since I'm currently testing the code, and will request review once any bugs are squashed. 
One question is the relevant placement of boxes. We currently don't have any multiplex libraries from PDX or cell line samples, but if/when we do, the info box about the sample type will be printed _before_ the warning that the library contains multiplex samples. Do we want to move the multiplex warning to be above the sample_type info box?

Update sample_type printing logic to handle multiplex samples

---

bin/merge_sces.R
bin/sce_to_anndata.R
merge.nf
templates/merge-report.rmd

Closes #681
This PR addresses issues raised about handling merged object during AnnData export:
1) In `merge_sces.R`, I ensured that `colData` column is called `suspension_type`, not `seq_unit`, and I updated `merge-report.rmd` accordingly.
2) I added a flag to `sce_to_anndata.R` to turn on in `merge.nf`.
3) I added a function `format_merged_sce()` to `sce_to_anndata.R` to format merged objects differently than single objects. This function only updates the reduced dim names, but even so I think the modularity is useful in case we ever want/need to change something else. Also, I use this function for altExps too. We don't expect reducedDims in the altExp so it really has no effect, but again one day we might need to add something else so I thought mirroring the code between main/altexp …

Update merged object for anndata export

---

modules/classify-celltypes.nf

Hot fix into `main` to remove duplicated code that snuck in there during a merge.

Remove duplicated code in cell type module

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/main_qc_report.rmd
templates/qc_report/utils/celltype_functions.rmd

Closes #663 
This PR adds a quick sentence to the top of the QC report if CellAssign was attempted but not run, where relevant
While I was here, I also added a `warning=FALSE` for an area in the UMAPs that was printing a warning (but code is all fine) that users don't need to see.
Here's how the sentence I added looks:
---

Add cellassign note to QC if not run

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/main_qc_report.rmd
templates/qc_report/umap_qc.rmd
templates/qc_report/utils/report_functions.rmd

Closes #618
Closes #620 
This PR makes two viz changes to the QC report:
- For #620, I updated the miQC plot line thickness as described in the isssue
- For #618, I updated the UMAP point size. I explored a variety of different numbers of cells and tweaked numbers accordingly. In the attached zip here, I include a bunch of reports where the file name contains the number of cells. All these reports include the update miQC line sizing, too.
- Once we agree on the point sizes, I will port the code defining the umap point sizes into the cell type supplemental report. I feel like we might want to put that in a function for Future Us, which might entail making a new `utils/report_functions.rmd` file? Thoughts?
Let me know what you think of sizing choices! …

QC report aesthetic updates

---

components/dictionary.txt
external-instructions.md

Closes #646 
This PR adds external instructions for the `merge.nf` workflow. Let me know about the level of detail and the order in which I provided information. Also, am I missing anything..?
Also, do we want to indicate in the repo's `README` that this workflow exists? Since other `README` updates are coming down the line (https://github.com/AlexsLemonade/scpca-nf/issues/619), I wondered if we should wait until those additional changes happen. Or, since we already link the external instructions in the `README`, it may not be necessary at all.  
Primarily requesting Ally for review here, but @jashapiro please feel free to chime in if you have any wording/organizational suggestions!

Add merge.nf external instructions

---

templates/merge-report.rmd

This PR addresses a few small merge report bugs that came up when working on updating the ScPCA test data.
- This is the first time running through a project with _both_ multiplex and non-multiplex samples as well as _multiple_ suspension types (we now have cell & nucleus in there). So I fixed a few bugs related to that:
- Some places where we had `%in%` should have been `==`; when determining if a row is multiplexed in `coldata_df`, we should only compare to that same row's value for `additional_modalities`. 
- When determining facet UMAP size, we have to count the number of libraries (`tech_table$`Number of libraries`); in the data we've explored so far this data frame had only 1 row. Here, it has multiple because of multiple suspensions. So I now `sum()` this column.
Also, `RMarkdown` …

Fix merge report bugs related to multiplexing

---

templates/merge-report.rmd
templates/qc_report/celltypes_supplemental_report.rmd

edit- closes #701 
While looking over the reports shared here https://github.com/AlexsLemonade/ScPCA-admin/issues/716#issuecomment-1953118312, I noticed that the CellAssign/SingleR heatmaps were missing a legend. This PR restores that legend by adding a quick argument to the heatmap function that says to always retain the legend.
Rendered report -  
[celltypes_supplemental_report.html.zip](https://github.com/AlexsLemonade/scpca-nf/files/14360330/celltypes_supplemental_report.html.zip)
Also, I reverted a change I made in https://github.com/AlexsLemonade/scpca-nf/pull/697; We definitely didn't need that `not_multiplexed` variable I made. I don't really recall/understand what I was experiencing that I thought we needed it, but we really don't need it. `eval = !multiplexed` works just fine.

Restore heatmap legend

---

CONTRIBUTING.md

Closes #695 
Here I've added a small section about CI into contributing. I nested this inside the PRs header and mentioned both required workflows and the pre-commit ci workflow (do I still have it correct that passing is not mandatory? I don't have access to Settings here so couldn't tell for sure).
Let me know if this is the right place in `CONTRIBUTING.md` to have added this, as well as any details to be expanded upon or reduced.

Add CI to contributing

---

merge.nf

Closes #704 
Short and sweet, flips order in the `merge.nf` publishDir so, for merge ids that are projects, their merged objects will be in the project directories.

Update merge publishDir

---

config/process_base.config
config/profile_ccdl.config
modules/classify-celltypes.nf

I think the issue with https://github.com/AlexsLemonade/scpca-nf/issues/709#issuecomment-1977033313 was that we set the max memory in two places: in the base profile for a default, but also in the ccdl profile. So I dropped the base back down and upped the ccdl profile to 1TB, which will hopefully do the trick.
I also changed the label to  `mem_512`, because that better reflects the content.

Bump memory for CCDL only

---

.pre-commit-config.yaml
bin/add_celltypes_to_sce.R
bin/add_demux_sce.R
bin/add_submitter_annotations.R
bin/classify_SingleR.R
bin/cluster_sce.R
bin/filter_sce.R
bin/generate_unfiltered_sce.R
bin/merge_sces.R
bin/post_process_sce.R

CLoses #710
Here I changed all compression of SCE RDS files from gzip to bz2, with the exception of merged files, which I left alone with their current faster but less efficient compression algorithm. (Noting also that the gzip there is already set for low compression, high speed)
I also removed the miQC model from the metadata of the processed data only, and from merged objects. I don't think it will be there in normal processing, but it seemed reasonable to remove in case we want to run the merge script on filtered data at some point.

Reduce SCE file sizes

---

config/profile_ccdl.config
internal-instructions.md
merge.nf
nextflow.config

Closes #705 
This PR adds the capability to specify runs, libraries, and/or samples to include when creating a merged object for a ScPCA project. First, we filter to any libraries that are in a specific project and then I filter to either include all runs or specify based on a parameter. 
I did choose to add a `merge_run_ids` parameter here rather than use the `run_ids` parameter set for the main workflow. The reason is because I noticed we have a default list of test runs in the ccdl profile, rather than using the `All` setting. So if you don't use the flag for `run_ids` then it will only include the test runs we specify in the profile. We would need to remember to always include `--run_ids All` when running the merge workflow, and I don't think we want to have to do that every single …

Specify merging only specific runs from a project

---

bin/merge_sces.R
merge.nf

Closes #716 
Closes #717 
Here I added a line to filter out any projects that have multiplexed libraries from the channel that is used as input to create merged objects. 
Because we have decided against including multiplexed libraries being included in merged objects, I removed any support we had for merging multiplexed libraries in the `merge_sces.R` script. I was a little torn on if we should keep this, but if the plan is to eventually create merged objects for all non-multiplexed libraries in a project, then we don't need this anymore. I can add it back if we want the flexibility to use it in the future, but I think a better change to that script would be to spit out an error if any libraries being merged contained multiplexed data when we address #718. 
As part of that, I also removed …

Skip merging projects with multiplexed libraries

---

config/process_base.config
config/profile_ccdl.config
modules/classify-celltypes.nf

Closes #709 
Here I added a new label, `max_mem` that uses the 96 gb on the first try and then increases to use the max memory on the second and third try. I'm testing this now, but also waiting for the other test run to actually complete to make sure this solves the problem. I just wanted to get this filed in case we are good to make these changes tomorrow.

Add max_mem label for Cell Assign

---

bin/generate_unfiltered_sce.R
components/dictionary.txt
examples/README.md
examples/example_sample_metadata.tsv
external-instructions.md
templates/qc_report/celltypes_supplemental_report.rmd

Closes #713 
Closes #707 
Here I'm making a few fixes to the workflow: 
- I added a sentence about not having tumor cells in the supplemental cell type report. This is the only place we explicitly talk about references, so I chose to include it only in the supplemental and not in the main report too. 
- I updated `generate_unfiltered_sce.R` to handle missing columns for `is_cell_line` and `is_xenograft`. If both are missing, then `Not provided` is used as the `sample_type`. 
- I will note that we use the `is_cell_line` column specifically when determining if cell typing should be skipped, so I think we do want to note that those columns can be included, even if they aren't required. I accounted for them in the example metadata and readme and then also added a note about it to the external …

Handle empty sample type columns and add sentence about references not having tumor cells

---

config/containers.config
external-instructions.md
internal-instructions.md
nextflow.config

Related to #654, here I'm updating the version tag and using the latest `scpcaTools` container.

Update version tag and scpcaTools container

---

bin/generate_unfiltered_sce.R
modules/af-rna.nf
modules/qc-report.nf
templates/qc_report/main_qc_report.rmd

In processing projects through v0.8.0, I found two bugs that needed to be addressed. 
- The first was we are trying to adjust the linewidth on the miQC plot, independent of if the miQC plot just plots the metrics or the models. If the metrics are plotted without the model, then no lines are present to adjust. I just moved that to be within the `if` statement that actually creates the miQC plot with the model. 
- The second was an extra `&` that seemed to be causing an error in evaluating the `sample_type` for multiplex samples. When I removed this then things worked as expected. The double & only looks at the first element and with multiplex we have a vector. 
- While I was here, I bumped up the memory usage for the fry quant process and qc report, since we were seeing a reasonable number …

Fix bugs in v0.8.0

---

bin/predict_cellassign.py
bin/sce_to_anndata.R
external-instructions.md
merge.nf
modules/classify-celltypes.nf
modules/export-anndata.nf

This PR should accomplish the main code changes required for #736.
I basically just searched for `hdf5` and updated most of those to `h5ad` as appropriate. The other "major" change was to the arguments for the `predict_cellassign.py` script, which I changed to be more consistent with other scripts and just use `anndata_file` rather than referring to the extension itself.
I updated the docs in this repo that referred to hdf5 files here too. But of course there are other docs changes that will be required.

Change Anndata extension to h5ad

---

bin/merge_sces.R
bin/sce_to_anndata.R
config/process_base.config
config/profile_awsbatch_auto.config
merge.nf
modules/classify-celltypes.nf
nextflow.config

Now that one of the merges has completed successfully, it was time to submit the changes I included to reduce memory usage during the merge. 
- I moved some of the SCE trimming to when we read in the files (though I realize this won't matter now that we don't have the miQC object in processed data anyway) .
- I also removed a place where we duplicate the list unnecessarily.
- In probably the biggest effect, I remove the `sce_list` once the merged object is created.
- Threw in some `gc()` calls.
I also added an explicit `long_running` tag to shift to the priority queue more quickly, and bumped up the `mem_max` base memory.

Reduce merge memory a touch

---

bin/add_celltypes_to_sce.R
bin/sce_to_anndata.R
modules/classify-celltypes.nf
templates/qc_report/main_qc_report.rmd

Closes #731 
Here I'm making sure we skip trying to run CellAssign if a processed object only has 1 cell. The problem is that we can't convert an object with 1 cell to an AnnData object, so then there's no AnnData object to use as input to CellAssign. 
To handle this I added a check for the number of cells in the SCE object in `sce_to_anndata.R`. If < 2 cells, then the script just quits and doesn't do any conversions. This means no `.h5ad` file gets created. If that's the case then we skip running the `predict_cellassign.py` script and just make an empty predictions file to output from the process. Then when annotations get added to the SCE object, if the predictions file is empty, all cells get annotated with `Not run`. This is the same value we use when CellAssign isn't run because of …

Skip CellAssign if only 1 cell

---

bin/sce_to_anndata.R

In generating test data, I ran into an error because we missed updating the file extension in one place. This updates the check for the extension for the feature file.

Account for .h5ad in output feature file

---

bin/sce_qc_report.R

Apparently, with our test data using `hashedDrops` doesn't assign cells to any of our samples. This prints out an empty list again, which we want to avoid. I checked, and using `HTODemux` only assigns cells to one sample but not all of them. This leads to a list with just one value while the list of sample IDs is longer. This would mean there is no way to match which cell count goes to which sample. 
If no cells are assigned, we should set to 0 rather than having an empty list. This PR makes that adjustment by looking for any missing sample IDs and then assigning those to 0.

Account for no cells being assigned to a sample when demultiplexing

---

config/profile_example.config
internal-instructions.md
main.nf

When working on generating the updated example data for #748, I found a bug in `main.nf` where we were missing a `params.` call before a variable. I also realized we were missing the cellhash pools files in the example config, so it was looking for a file that doesn't exist and giving an error. I added the cellhash pool file that we have in examples to S3 and then to the profile for example. Alternatively, I could have just left it empty in the example config, but since we have the file we mine as well use it. This means that all example metadata files should now also be on S3.

Fix bugs with generating example data

---

bin/add_celltypes_to_sce.R
bin/sce_qc_report.R
templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/main_qc_report.rmd

While processing data for the Portal, I found an object that only has 1 cell in the processed object so it tested out some of the code we added to handle that scenario. There were a few issues that I had to fix to get this to work and then I also made a design change that we will need to decide on if it's the right move or not. 
- If any object only has 1 cell then it doesn't have PCA or clusters. We have a check for PCA/UMAP when generating the reports, but not for clusters. Here I added a `has_clusters` variable to make sure no plots that use clusters are created. 
- There was also a small error in the `add_celltypes_to_sce.R` where we were still attempting to add in cell type annotations if the predictions file was empty. So I adjusted the logic there to account for the missing file …

Fix bugs for dealing with processed objects with only 1 cell

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/main_qc_report.rmd
templates/qc_report/umap_qc.rmd

In #755 I made a fix to the UMAP point sizes variable that used the global value for a variable as the default for the function. I did that because I didn't see that variable defined anywhere in the report that uses that function, but it's defined in the main and supplemental report. With that change we need to actually define the point size when calling the functions to plot UMAPs. Otherwise, we get a failure when plotting a UMAP, since `point_size` isn't defined. So here, I'm just adding those lines. We could revert the change I made in #755, but I think this is more specific and easier to track what's being defined where, something that tripped me up when I was going back and making fixes in #755.

Define umap point size when creating cell type umaps

---

bin/merge_sces.R
merge.nf

In merging the processed data for a project for the Portal, I came across a small error in the `merge_sces.R` script. R was complaining about calculating the `sum()` of a list so I just added an `unlist()` and that fixed that problem. 
The other precautionary measure I took here is to ensure that if a processed file exists but its size is 0, it's not actually included in the merging process. I can imagine that causing problems down the line if we try to read in an empty file. I also added a warning message that should print out any libraries that are not going to be included in the object.

Fix some merge bugs

---

bin/add_celltypes_to_sce.R
bin/merge_sces.R
bin/move_counts_anndata.py
bin/sce_qc_report.R
merge.nf
templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/main_qc_report.rmd
templates/qc_report/umap_qc.rmd

When working on OpenScPCA-nf, I found that when we move raw data in the processed data, we are leaving in place the original "logcounts" layer, making it meaning we have two copies of it around. 
This PR removes that duplication (and merges in changes from `main` to `development`)
Unless we were supposed to leave it for some reason, I think it should save us some space! By my metrics (and logical expectation, nice when they match) this saves ~1/3 of the space for the AnnData processed objects.
I couldn't find any reference to the `layers` in our docs, so this change should not require any updates there.

Delete duplicate layer in AnnData objects

---

config/profile_ccdl.config

Closes #761 
I did some testing of the workflow using the changes from #762 and everything ran successfully 🎉 I did not however run anything through `CellAssign`... I can do that though if we would like before closing the testing out. 
To do the testing I was going to create a new test profile, but we already have a `ccdl` profile that specifies a subset of run IDs to run. So rather than create a new profile I'm using the existing `ccdl` profile but have updated the `run_ids` param to include one sample or library from each of the possible modalities - one single-cell with bulk, one CITE, one multiplexed, and one spatial. I think I got everything?

Test new docker image and add test samples to profile config

---

bin/generate_bulk_metadata.R
modules/bulk-salmon.nf

Closes #766 
Closes #764 
Here I just added a `bulk` directory to the existing `publishDir` for the bulk output. This will mean both the quant and metadata files will be saved to `project_id/bulk`. 
While I was here I decided to update the order of the bulk metadata to match the project metadata and `single_cell_metadata.tsv` files that are on the Portal.

Move bulk output to separate bulk directory

---

templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/main_qc_report.rmd
templates/qc_report/utils/report_functions.rmd

Closes #765 
This PR adds a function to create a sample metadata table to `report_functions.Rmd` and then uses that function in both the main QC report and cell type report to create the sample metadata table. The table is shown for any non-multiplexed samples. Otherwise, we have a nice little blue box that says the metadata will not be displayed since the sample is not demultiplexed. I took the wording from the merge report where we also don't show sample metadata. 
The table is formatted in the same way we have our other tables and I was able to successfully add links for the ontology IDs 🎉. I also accounted for missing ontology IDs and only provide a link if an ID was provided. 
In the main report I adjusted a few headers to account for adding in this table. 
Questions for reviewers: …

Add sample metadata tables to reports 

---

bin/move_counts_anndata.py
bin/predict_cellassign.py
bin/reformat_anndata.py
bin/sce_to_anndata.R
merge.nf
modules/export-anndata.nf

Closes #773
I'm filing this as a draft because I have not yet really tested it, but I wanted to get something up while it was fresh in my mind.
The goal here is to improve the compatibility with scanpy as described in #773, so I have done 4 main things:
- Use lower case for `X_pca` and `X_umap` to match scanpy.
- Convert the PCA and UMAP matrices to numpy matrices.
- add a `highly_variable` column to the `var` table
- Add PCA metadata to `uns`
The last step involves exporting the variance explained data and then importing that separately, with the assumption that the PCA was centered and highly variable genes were used. I could (and probably should) make those assumptions into arguments for the script just to be safe and maybe a bit future-proof. 
There are probably also a few places …

Improve scanpy compatibility

---

merge.nf
nextflow.config

Closes #776 
In processing data for the Portal, we have seen that projects with > 100 libraries do not successfully run through the merge workflow due to what we think is limitations of the packages we use. We don't actually know the number of libraries that cause the problem and it's probably based on number of cells and how big the actual matrices are, but as of right now we do not include any [projects with > 100 libraries as merged objects on the Portal](https://scpca.readthedocs.io/en/stable/faq.html#which-projects-can-i-download-as-merged-objects). 
Because of this, I'm adding a parameter to specify the maximum number of libraries allowed in a merged object and setting the default to 100. If any projects have more than this, then we will print a message to the log files and skip …

Add parameter for maximum number of libraries to allow when merging

---

bin/reformat_anndata.py
bin/sce_to_anndata.R
external-instructions.md
internal-instructions.md
modules/export-anndata.nf
nextflow.config

Here I'm updating the release version to be v0.8.3. 
I also did a test run and found a small bug where we were trying to access hvg's in the ADT AnnData objects, which don't exist. So I fixed that by using the `--hvg_name "none"` option.

Update versions and bug fix for v0.8.3

---

merge.nf

I was going to generate all merged libraries and projects that I wouldn't expect to reach the limit of 100 libraries were not getting processed. Looks like we were counting all libraries in a project including any CITE seq, spatial, or bulk. Here I just add a filtering statement to remove those libraries prior to counting how many are in a project. 
My plan is to merge this in to `development` and then into `main`.

Only count single cell libraries for max merged

---

merge.nf

One more fix for the merged object workflow. They have a different name for HVGs that need to be specified using the new reformatting script so I updated that here. Note that I tested this on an object that was failing and it worked as expected.

Account for different HVG name in merged object

---

main.nf
modules/af-features.nf
modules/af-rna.nf
modules/genetic-demux.nf
modules/starsolo.nf

When doing some testing related to #792 with newer versions of Nextflow, I got warnings that the `addParams()` function was deprecated, so I made some changes to remove that syntax, instead using `take:` to pass the values. Turns out I like this syntax better anyway!
closes #791

convert addParams to take

---

bin/merge_sces.R
lib/Utils.groovy
merge.nf

Following #799, here I am also filtering the merged data to not include samples with 2 or fewer cells. This turns out to be necessary for the calculation of tehe grouped PCA (at least that is what I think is going on).
I took a bit of a belt and suspenders approach here, checking both in the metadata during the workflow itself and in the R script where I check the SCEs before merging.
There is also a little cleanup in one of the `Util` functions so it doesn't throw an error if a file doesn't exist.
I did a small test with this and it seemed to work, but a larger test is still in progress, which is why I am filing this as a draft.

Add minimum number of cells (3) for merge

---

.github/workflows/nextflow-stub-check.yaml
.github/workflows/spell-check.yml
README.md

Closes #805 
This PR updates two workflows:
- The stub workflow gets bumped from artifact v3 -> v4
- The spellcheck workflow gets replaced with a new workflow using our spellcheck repo
- I did not delete the spell check script since it's used by pre-commit. If we prefer to also use the spellcheck repo for precommit, then we'd need to add a `.pre-commit-hooks.yaml` file to it, which maybe we should just go ahead and do? 
I'm opening this as a draft to confirm first that the GHA works and detects a typo I added in.

Update GHA artifacts

---

bin/generate_unfiltered_sce.R
templates/qc_report/utils/report_functions.rmd

Closes #808 
This PR makes some minor adjustments to how we handle `sample_type` to account for samples that are both a PDX and a cell line. I modified the existing code so that the `sample_type` option can now be a vector with `cell line` and `patient-derived xenograft`. 
I had to make a small change to the table in the report to combine into a single string, otherwise it printed two columns for the sample table. I tested this with the sample this applies to and did a test run using one of each sample type and everything looks as expected. 
Here's an example of the report for the affected sample. 
[SCPCL001201_qc.html.zip](https://github.com/user-attachments/files/18540965/SCPCL001201_qc.html.zip)

Account for samples being both PDX and cell line

---

.github/workflows/nextflow-config-check.yaml
.github/workflows/nextflow-stub-check.yaml
.gitignore
config/containers.config
config/process_base.config
config/profile_awsbatch.config
config/profile_awsbatch_auto.config
config/profile_ccdl.config
config/profile_stub.config
examples/user_template.config
external-instructions.md
nextflow.config
nextflow_schema.json

I had a branch from a bit ago where I updated a few things to new Nextflow standards, and I thought it might make sense to get this in as part of #810.
The changes here implement using the "new" resource limits in Nextflow. 
While I was at it, I also updated the schema to match the current parameters, which included removing what I think is an unused `CONDA_CONTAINER` parameter.
I also updated some of the manifest to use the updated format, with additional information including the doi for the paper!

Use resource limits and update manifest and schema

---

bin/tximport_bulk.R
components/dictionary.txt
external-instructions.md
modules/bulk-salmon.nf

Closes #815
I was looking at `scpca-nf`, and realized that the changes to add TPM output were quite minimal, so I went ahead and did that. I left the count file name unchanged, despite its ambiguity, and simply added one more output file, in the same directory. 
Since the script name seemed a bit out of date, I modified that as well.

Add bulk TPM output to scpca-nf

---

nextflow.config

Apparently the contributors field requires specific formatting, and I had it wrong. What I had works fine for local runs, but causes trouble when using Seqera Tower. This should now be the correct format.

Fix contributors formatting

---

modules/spaceranger.nf

Closes #818, if we want to. 
This is a very small PR, but as noted in #818, it may actually have some substantial savings both in storage costs and maybe even a bit of run time (since it prevents copying files to and from the work directory). 
I can't see a downside at the moment, but I am well aware I could be missing something.

Remove SPATIAL_RNA_COUNTER_CS

---

bin/sce_metrics.R
bin/sce_qc_report.R
main.nf
modules/publish-sce.nf
modules/sce-processing.nf
workflow-testing.md

Closes #832 
Here I added a script for calculating the tracking metrics described in the `workflow-testing.md` document.
I added a script to gather the statistics and perform calculations as needed and integrated it into the QC report process of the workflow, which I renamed to make the fact that is the "publishing" part of the workflow.  I added a couple more stats that I thought were worth including, notably the spliced counts. I also made the adt counts a dictionary so that if there were more than one altExp, we will be ready (at least with this part; lots of other changes would still be needed).
As long as I was renaming processes, I went a bit further, renaming some of the confusingly named "merged" processes with names that better reflect that they are for experiments with feature …

Add metrics calculation script

---

bin/add_celltypes_to_sce.R
config/reference_paths.config
modules/classify-celltypes.nf
nextflow_schema.json
references/README.md
references/consensus-cell-type-reference.tsv
references/panglao-cell-type-ontologies.tsv

Closes #824 
Here I am adding the consensus cell types to the processed objects within the `add_celltypes_to_sce.R` script that gets used to add the `SingleR` and `CellAssign` cell types to the `colData` of the object. 
- I added two new parameters, one for the panglao ontology ID reference and one for the consensus cell type reference. The parameters for both of these files point to their location in `OpenScPCA-analysis`.
- Since part of creating the consensus labels included assigning ontology ID terms to the cell types in `PanglaoDB`, I first am adding in a new column, `cellassign_celltype_ontology` which includes the assigned ontology terms for the `CellAssign` cell types. 
- Then if both `CellAssign` and `SingleR` results exist, I add in the consensus annotation and ontology. 
- If …

Add consensus cell type assignments to processed objects

---

external-instructions.md

Closes #825 
Here I just added a few lines to the external instructions doc to mention that cell type assignment includes SingleR, CellAssign and the consensus annotations. I kept it pretty brief and just mention that we provide them with a link to the module that describes them in more detail. 
The rest of the instructions are more focused on how to perform cell typing, which has not changed since making this addition so there wasn't much else to update. We also already documented the references in the `references/README.md`.

Add a brief explanation of consensus cell types to instructions

---

config/containers.config
external-instructions.md
internal-instructions.md
nextflow.config

Closes #838 
Towards #837 
Here I'm bumping the `scpcaTools` container to the latest release, `v0.4.2`. I did a test run with the container using `edge` right before I did the release and things work as expected for both the main and merge workflow. 
I also updated the version tag throughout the config and docs in preparation for the release.

Use new scpcaTools container and bump version to v0.8.7

---

bin/sce_metrics.R

Closes #850 
Here I am updating the metrics file to add consensus cell type results. I also added some more fields from the `_metadata.json` file, in case we later want to add those to the change report. Finally, I made sure that the reference files are not filled in as NULL, as that would remove the field from the output. This last change is a bit of "belt and suspenders" with the `default = NA` change in #861, but it seemed worth throwing in.
Are there any other fields that we should be adding in while this is open?

850 Add consensus cell type fields to metrics script

---

scripts/compare-metrics/compare-metrics-template.rmd
scripts/compare-metrics/compare-metrics.R

closes #852 
I created a set of test files at `s3://nextflow-ccdl-results/metrics-test` which includes projects 1-10. I made this the default for the wrapper script for now. 
I swapped around a few samples, which results in one processing change in the current report, and the removal of lots of projects means there are a lot a changed files.
While I was testing this, I found a few little errors/optimizations that I cleaned up as well.
- I list only the `results` subdirectory, which saves a fair amount of time. It still takes a while to download and parse all the json files, but the listing is _much_ faster.
- I also made the regex more specific, as it turns out there are some `*_metrics.json` files that are produced by Space Ranger, which we want to be sure to skip (these are really only …

Make test files default (for now) and updates to metrics report

---

.gitattributes
.gitignore
CONTRIBUTING.md
cavatica/README.md
components/dictionary.txt
pixi.lock
pixi.toml

Closes #857
To manage the dependencies for porting to Cavatica, I here set up some `pixi` environments, and added documentation about their use. 
Since we did not already have a `conda` environment defined in this repo, this seemed like a good place to pilot using `pixi`, and I will say that I found the experience pretty enjoyable. It is _much_ faster than `conda` or `mamba` and I like the fact that the environments are defined by the directory rather than given separate names, more like `renv`. I also really like that it automatically updates the environment to match the lockfile when launched, so you don't have to worry about using an old version of the environment if it was updated by another user.
It also makes it relatively easy to define multiple environments, which I have taken …

Add pixi environments for Cavatica (and general development)

---

bin/sce_metrics.R
scripts/compare-metrics/compare-metrics-template.rmd

Here I am adding the cell count change summaries and detail table to the change report. This is the first half of #853 (but does not fully close it)
There was a bit of error correction I had to do because we are using unboxed JSON for the metrics file, which seems to be causing a bit of a challenge with NA values. But maybe only sometimes? The issue is that we have a few NA values for miQC pass values, which are getting read in as strings. In my testing if we were to export without `auto_unbox`, this would go away. So I added that change for some simplification of reading the file in the future, but for now I had to deal with what we have so there is some added code to be sure the NA values are treated appropriately and the columns turned back into simple vectors where needed. I did pull …

Add cell and read count reporting to change tracking notebook

---

scripts/compare-metrics/compare-metrics-template.rmd

closes #853 
Here I am adding the read count tables and plots to the report. These follow the same general form as the cell counts, but there were a few extra wrinkles for altexp reporting. The main thing was adding a line to break the list column into a set of columns based on which altExp was being used. `tidyr:unnest_wider` was exactly what I was looking for!
I simplified a few other things along the way: the effort to sort the plots non-alphabetically seemed not worth it, so I ended up removing the code that was dealing with factors there.
One important decision I want feedback on was whether or not to include samples that had cell count changes in the read count tables and plots. It seemed obvious to me that any changes in cell counts would result in changes in read counts, so it …

Add read counts

---

.github/workflows/nextflow-stub-check.yaml

As a temporary fix for #867, we want to prevent the action from using the latest version of Nextflow, so here I am pinning to the last working version of Nextflow until we can do some debugging.

Pin nextflow version

---

.github/workflows/nextflow-stub-check.yaml
modules/bulk-salmon.nf
modules/bulk-star.nf

Closes #867
The with #867 was actually closing a longstanding bug where glob expressions didn't actually check if the files exist. Now they do, so we were getting failures with non-paired-end reads. The fix is to only check for existence when we expect them. This worked with a local stub check and Nextflow 25.04, so I expect it to work here as well.

Only check for paired end files if paired end used

---

examples/example_multiplex_pools.tsv
examples/example_run_metadata.tsv
examples/example_sample_metadata.tsv

Closes #872 
Here I'm adding example 10X flex data to the folder of example FASTQ files and accounting for these two new libraries in the example metadata files. 
- I downloaded the input FASTQ files for a [singleplexed example](https://10x.vercel.app/datasets/Human_Kidney_4k_GEM-X_Flex) and [multiplexed example](https://10x.vercel.app/datasets/80k_Human_PBMCs_PTG_MultiproPanel_IC_4plex) and copied the FASTQ files to `s3://scpca-references/example-data/example_fastqs`. 
- These are both examples that use the v1.1.0 probe set for 10X flex. 
- This was the smallest multiplexed example that I could find that also uses the most recent probe set. It does have feature barcoding too, but that information is in separate FASTQ files. So I just copied over the gene expression FASTQ files and …

Account for 10X flex example data in metadata

---

build-index.nf
config/ccdl_inputs.config
config/reference_paths.config
internal-instructions.md
references/ref-metadata.tsv
references/scpca-refs.json
references/scripts/create-reference-json.R

Closes #874 
Here I am making a number of adjustments to accommodate building the index for `cellranger` with the fasta from Ensembl v110. I definitely could have just added a new entry to the metadata file and re-ran the workflow and generated all the indices for this Ensembl version, but we don't really need to store any extra index files. And with the changes I'm making here, it should make our index building more modular. 
- I added new columns to the `ref-metadata.tsv` file that are boolean columns indicating whether or not to include an index specific to salmon, cellranger, or star for that reference version. 
- I updated the script that builds the ref json file to only include paths to relevant files and everything else is null. 
- The `build-index.nf` workflow now uses those new …

Build new Ensembl v110 cell ranger index

---

references/scpca-refs.json
references/scripts/create-reference-json.R

Based on https://github.com/AlexsLemonade/scpca-nf/pull/881#pullrequestreview-2865394976, I went ahead and updated the json file and the script to make the json to use empty strings instead of Null.

Use empty strings instead of null in refs json

---

components/dictionary.txt
external-instructions.md
internal-instructions.md

Closes #888 
Here I am adding some documentation around running samples with 10x flex. 
- For internal instructions, I just added a section that mentions the example datasets and how to run the workflow to process those samples. I didn't think it needed much, but I just wanted to note where the example datasets came from and also how to actually run those samples with the `example` profile. 
- While I was here, I updated the external documentation to note that flex samples can be used. 
- I updated the `technology` column options to include 10x flex.
- I added a section within the special considerations section for using 10x flex data. The main thing I wanted to note is that `cellranger multi` is used and how multiplexed samples are dealt with. Let me know if you think there is more that …

Add some documentation around 10x flex support

---

external-instructions.md
modules/export-anndata.nf
modules/publish-sce.nf

Closes #901 
Closes #907 
Here I'm updating the two processes that publish the SCE and AnnData files to rename any multiplexed 10x flex samples to have `<library_id>-<sample_id>` as the file prefix instead of just library id. This was a pretty simple fix and I just checked for the 10X flex technology before defining the prefix to use for the files. Is there a different approach that would be preferred? 
While I was here, I went ahead and updated the instructions to use Docker to address #907. I mostly copied the same language we have in the spatial section, but updated it for cellranger.

Update 10x flex multiplexed filename outputs and document docker requirements

---

examples/example_project_celltype_metadata.tsv
external-instructions.md

In order to be able to run the 10X flex example data with cell typing, we need to use the right model files in the example celltype metadata. This updates that file to use the new filenames and fills in references to use with `project02`, which corresponds to the flex example data.  
I also made some small edits in the external instructions to account for the filename changes.

Update example metadata to use new singleR model files

---

config/ccdl_inputs.config
config/ccdl_profiles.config
config/containers.config
config/reference_paths.config
nextflow.config

While working on #893, I ran into a number of validation errors while using the Nextflow VScode plugin. The crux of these was that we were apparently using `includeConfig` a bit more liberally than they would have liked, such that we were including "fragments" of config files that would not be valid on their own.
From https://www.nextflow.io/docs/latest/config.html:
> Config includes can also be specified within config blocks. However, config files should only be included at the top level or in a profile so that the included config file is valid on its own and in the context in which it is included.
This PR just includes the cleanup to pass validation, which mostly means moving the include blocks up a level to either the top level or the top level of a profile, and adding the appropriate …

Update Nextflow configs to use recommended structure

---

bin/add_celltypes_to_sce.R
scripts/aws/run_nextflow.sh

A couple of small fixes for the scpca-nf running in the new account.
The main one is the change to accommodate the new style of cell type reference paths. We might need to incorporate that one into the dev branch sooner rather than later, but probably not right away. I mostly started from copying the version in the flex branch, but I made a few changes to deal with the potential for either file name format. I also added the extra fields to the metadata, because why not. 
The other change is just fixing the AWS secret name.

Small fixes for scpca-nf

---

bin/detect_doublets.R
bin/filter_sce.R
modules/sce-processing.nf

Closes #929 
In this PR, I am adding code to run the `detect_doublets.R` script into the workflow. Given that we should probably be running this on filtered instead of processed files, I decided for a first stab to take the path of absolute least resistance and just add the script to run inside our existing `filter_sce` process, which does use the `slim` container (for which `scDblFinder` inclusion is still pending in https://github.com/AlexsLemonade/scpcaTools/pull/305). This code is therefore analogous to how we add in submitter annotations in the unfiltered processes, e.g.:
https://github.com/AlexsLemonade/scpca-nf/blob/8a85702f7c3e616d1d73335d4139d3c72fabfd4e/modules/sce-processing.nf#L4-L45
It reads in an SCE, adds some colData, and exports the SCE to the same input file. As such, I …

Incorporate doublet detection into workflow

---

bin/merge_sces.R

Closes #930 
This PR updates our list of columns to keep in merged SCEs with the 2 new columns we added with doublet info:
https://github.com/AlexsLemonade/scpca-nf/blob/8b10cadafbf387a6457d7d498758e7790c09c11e/bin/detect_doublets.R#L74

Retain the doublet columns in merged SCEs

---

templates/qc_report/celltypes_qc.rmd
templates/qc_report/main_qc_report.rmd

Closes #933 
I added the UMAP for the consensus cell types to the main report and the supplemental report. Just like with the tables, I show the SingleR/CellAssign UMAPs in the main report if there are no consensus cell types. 
The only tricky thing here was that I didn't love the text we show if we are only showing consensus cell types in the main report (if we don't have submitter). I made a small change to just remove one of the lines describing multiple UMAPs if we are only showing consensus.
Here's the example reports again: 
[celltype_reports.zip](https://github.com/user-attachments/files/21517177/celltype_reports.zip)

Update UMAPs to include consensus cell type annotations

---

cavatica-instructions.md

There was a missing `/`, so this link to Seven Bridges documentation was not working as intended.

Fix link in cavatica-instructions.md

---

.github/workflows/nextflow-stub-check.yaml
templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/umap_qc.rmd
templates/qc_report/utils/report_functions.rmd

Stacked on #950 
Closes #948 
Here I'm moving the clustering UMAP and heatmap to a separate `Unsupervised clustering` section to be shown in the supplemental report. This section appears after the cell label comparisons (see #950) and before the diagnostic plots. I included a statement warning users to interpret the clusters with caution. 
At first, I was skeptical about moving the UMAP with clusters out of the main report since people love to look at colorful UMAPs, BUT I don't think it's entirely helpful where it currently is in the main report. We include it within the cell type section as a UMAP before the faceted UMAPs. I think _if_ we include the UMAP in the main report, it should be its own section outside of the cell type section. Because we don't really trust these clusters …

Move clustering plots to a separate section

---

templates/qc_report/celltypes_qc.rmd

If there are no normal cells reported by the consensus cell type, we should not attempt to make the dot plot. Without any validation group annotation markers to plot that doesn't really make sense. This PR just adds a sentence to the dot plot description noting that the plot is not shown if everything is "Unknown" and then the plot is skipped.

Account for consensus cell types being all unknown in report

---

components/dictionary.txt
templates/qc_report/celltypes_qc.rmd
templates/qc_report/cite_qc.rmd
templates/qc_report/main_qc_report.rmd
templates/qc_report/multiplex_qc.rmd
templates/qc_report/umap_qc.rmd
templates/qc_report/utils/report_functions.rmd

Part 1 of #371 
Here I'm making a number of small changes to the main report to make things prettier. Mostly, I added tabs where I thought they helped de-clutter things without hiding too much and converted some tables to use `DT::datatable()`. 
Here's a zip file with three different versions of the main report - a regular single cell library with submitter annotations, a library with CITE-seq, and a multiplexed library: 
[reports.zip](https://github.com/user-attachments/files/21761997/reports.zip)
Here's an overview of the changes that I made: 
- I added tabs in places where we had related tables or plots. I find this really helpful for viewing the cell type tables and UMAPs!
- This includes a tab with the QC plots (knee plot, miQC etc) and I was a little unsure if we wanted to do this …

Add tabs and DT to the main report

---

bin/cellbrowser_config.py
modules/cellbrowser.nf
nextflow.config
nextflow_schema.json

closes #974
Here I updated the cell browser config file to include all of the cell type annotations, and made the default the consensus cell types. 
It seems like some of the code updates to find all of the celltype fields may not actually be required, as Cell Browser itself seems to auto-discover many of the fields, which I did not see before because the original files I was working with only had the clusters. But I don't mind having those annotations in the config files so I am leaving it as is. 
To see the new example browser, download the full set and display with some version of:
```bash
aws s3 sync s3://nextflow-ccdl-results/scpca/processed/cellbrowser cellbrowser
uvx --from cellbrowser cbUpgrade -o cellbrowser
```
You should see default labels by consensus cell types with the …

update cell browser config file with cell type annotations

---

.github/workflows/docker_cellbrowser.yaml

I managed to forget to actually specify the tags for the push, so that failed. Trying again!

Docker push fix: specify tags

---

bin/run_infercnv.R
config/reference_paths.config

Closes #1001 
This PR adds a script to run inferCNV, which I have locally tested with much success. The only code changes here are this R script. Here's a rundown:
- One thing I learned is that we don't actually need to _write out_the `annotations_file` as an intermediate step but it can be a data frame, so that's a nice upgrade from previous scripts that run inferCNV!
- I have wrapped running inferCNV in a tryCatch, and if it fails I touch a PNG file with the same name that inferCNV creates it has. I don't attempt any renaming but just take what inferCNV wants to call it
- I add three items to the SCE if infercnv runs successfully:
- the wide table goes into metadata
- a total_cnv column goes into coldata
- I also added another metadata field `infercnv_options` with a list of info that …

Add script to run inferCNV

---

bin/add_infercnv_to_sce.R

(formerly) ~Stacked on #1007~
Closes #1008 
This PR adds the next script for inferCNV, to add the results to an SCE object. This script is pretty small! It adds two metadata components (the wide cnv table and the infercnv options) which are loaded from an RDS file the first script exports, and it also adds the total_cnv column to the colData.

Add 2nd inferCNV script: Save results to SCE

---

bin/run-scimilarity.py

Closes #1027 
This PR just adds the script to run SCimilarity on a single processed H5 file and exports the TSV with barcodes, annotations, and min_dist. I mostly just copied from the existing script in [OpenScPCA-nf](https://github.com/AlexsLemonade/OpenScPCA-nf/blob/main/modules/cell-type-scimilarity/resources/usr/bin/run-scimilarity.py) and then just made sure it was executable. Next up, I'll add the process that actually runs this script.

Script for SCimilarity
