AlexsLemonade/scpca-nf

main.nf
modules/af-features.nf

This PR adds support for cellhash data, closes #7 
The change is pretty minimal: I added cellhash data to the cellbarcode list in `main.nf`, and made sure we included it asa type for "feature" data. 
I did simplify the UMI geometry map a bit as well, so that we can expect that to work in the future if there are other types that we want to support.

Add support for cellhashing

---

config/containers.config

closes #90
I updated scpcaTools image to 0.1.3, and did some minor rearranging of the containers config file.
I have tested this version of the workflow, and everything seemed to go as expected!

Update scpcaTools to v0.1.3

---

main.nf
modules/bulk-salmon.nf
modules/qc-report.nf
modules/spaceranger.nf
nextflow.config

This PR adds some parameter checks to the main workflow to catch what I thought were the most likely errors for now. It turned out in my mind that there really wasn't too much to check, but having the framework there was still worth doing.
Closes #105 (probably)
The most important check is for the presence of the metadata file, I think checking the format of that file is going to be a whole different can of worms, so I didn't do that at this point. My groovy skills aren't there yet.
We could check all of the reference files as well, but I didn't do that at this stage. I think I would want to figure out some loop for that, rather than a long series of `if`s, but I didn't get there yet. If we think that should be part of closing #105, I could do that as part of this PR, or add it as a …

Add parameter checks

---

README.md
config/process_base.config
config/profile_awsbatch.config
examples/example_metadata.tsv
examples/user_template.config
external-data-instructions.md
main.nf
modules/bulk-salmon.nf
modules/qc-report.nf
modules/spaceranger.nf
nextflow.config

Before the creation of v0.2.4 tag/release, this should make the `latest` branch have the same contents as main.
I realized that the better order of operations was to merge into `latest` _first_ and then tag _there_, so I actually just deleted the 0.2.4 tag, and we will merge this first, then tag and release from that branch.
Please review #130 first though, to catch a little error!

Merge v0.2.4 release into latest branch

---

README.md
external-data-instructions.md
nextflow.config

Since incorporating #148, we need to create a new release to be able to run the spatial samples. This PR just updates the version numbers in the documents specified in the release checklist to be v0.2.6. I am merging these to `main` and then I can create a PR to `development` after merging these changes. I tested opening a PR with the new changes incorporated into `main` in #148 and it showed only the one file that was modified as expected so hypothetically we shouldn't have any issues after these changes are merged.

Update version in config file and docs for new release 

---

README.md
external-data-instructions.md
nextflow.config

Here I'm prepping for the next release and updating the version in the relevant files to be `v0.3.1`. I will leave this in draft form and wait until #191 and #190 have gone in to merge this and then merge changes into `main` and tag the new release.

Update version to 0.3.1

---

README.md
config/containers.config
external-data-instructions.md
nextflow.config

Closes #215
Here I am updating the version number for the scpca-tools docker image (which is still building as I write this) and the version numbers of the package in prep for the next release.

Update version numbers

---

.github/workflows/nextflow-config-check.yaml
README.md
external-data-instructions.md
external-instructions.md
internal-instructions.md

Closes #235
I pulled the internal instructions out to a separate document, since that was causing some confusion/distraction for external users in testing. 
I also added a bit more content to the opening paragraph... a very low-key explanation of the main goals right at the top. 
I thought it made sense to do this before we got the next release out!

Update readme with a bit of sales

---

.github/ISSUE_TEMPLATE/release-checklist.md
bin/post_process_sce.R
config/containers.config
external-instructions.md
internal-instructions.md
modules/genetic-demux.nf
nextflow.config

Syncing changes for v0.4.1 to `main`. No new changes.

Sync changes to main 

---

integrate.nf

Closes #238 
Stacked on #274 
Here I'm adding the process to the integration workflow to integrate the merged SCE object using `harmony`. I'm using the same script added in #274, but with the method set to harmony. I didn't do anything too different here, other than I added a param for harmony covariate cols and set to `NULL` in the Nextflow workflow. Any other suggestions on how to deal with a default of no additional covariates?

Integration with harmony

---

bin/make_reference_fasta.R
build-index.nf
config/reference_paths.config
examples/README.md
examples/example_metadata.tsv
external-instructions.md
get_refs.py
internal-instructions.md
main.nf
modules/af-rna.nf
modules/bulk-pileup.nf
modules/bulk-salmon.nf
modules/bulk-star.nf
modules/sce-processing.nf
modules/spaceranger.nf
modules/starsolo.nf
nextflow.config
references/ref-metadata.tsv
references/scpca-refs.json
references/scripts/create-reference-json.R

Here I'm just syncing all of the changes we merged in #289 to the `main` branch. I created a new branch off `main` and then cherry picked the merge into `development` of that branch which contains all of the changes specifically related to supporting multiple organisms. 
I also cherry picked the changes in #320 and #321 so those are reflected here as well. 
The other changes that we've made since the last release are all related to integration and cell typing, so I want to keep those out of this release and just merge these changes in.

Sync support of multiple organisms to `main`

---

modules/af-features.nf

One more thing I missed for the release, skipping feature mapping and publishing the rad directory.

Sync skipping feature mapping to main

---

bin/filter_sce_rds.R
bin/post_process_sce.R
main.nf
modules/af-features.nf
modules/sce-processing.nf

Closes #293 
(Originally I envisioned this being the first of several PRs to close out #293 - hence the branch name - but now I'm thinking for any next filtering steps I'll want to open new issues, so we can close out this issue now.)
This PR sets up the initial code for filtering on CITE-seq data. The code has been tested and is all running :tada:. I made a couple choices here, and left some for discussion during review. 
- I currently am using an Rscript argument `adt_name` that should point to the CITE-seq altExp. Based on conversation in #311, I do not actually think this argument is needed, but I've stubbed it out in case we want it. 
- For the filtering itself, I decided to make the feature barcode third column optional, which may help avoid parsing errors. If that column is not …

Add initial steps for ADT filtering

---

external-instructions.md
internal-instructions.md
nextflow.config

This just preps for v0.5.1 and updates the config and docs with the correct release tag.

Update docs to have v0.5.1

---

external-instructions.md
internal-instructions.md
nextflow.config

Same as #339, just syncing changes to `development` too.

Sync development with v0.5.1

---

external-instructions.md

Sync documentation changes

---

bin/sce_qc_report.R

Closes #358 
Does what it says! Example output attached.
[SCPCL000365_metadata.json.txt](https://github.com/AlexsLemonade/scpca-nf/files/11899528/SCPCL000365_metadata.json.txt)

Add ADT filtering and normalization to metadata

---

config/containers.config

Closes #363 
Does what it says!

Bump scpcaTools version in config

---

external-instructions.md
internal-instructions.md
nextflow.config

Towards #385 
Version string bumps for next release

Update version to `v0.5.3` for release

---

bin/classify_cellassign.R

Closes #420 
Pretty much does what it says! I'm testing this now, and will request review once I have confirmed it works as expected.

Only save CellAssign celltype column to celltype column

---

templates/qc_report/umap_qc.rmd

Closes #448 
Short and sweet, no longer need to rename now that we are at Bioconductor `3.17`!

Don't rename UMAPs

---

external-instructions.md
internal-instructions.md
nextflow.config

Increase version number in `development`

---

lib/Utils.groovy

Following the minor issue raised in https://github.com/AlexsLemonade/ScPCA-admin/pull/656, we should properly handle blank values as well as `NA`

Handle blank values in parseNA

---

bin/cluster_sce.R
modules/af-rna.nf
templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd
templates/qc_report/utils/celltype_functions.R

**Stacked on #491**
Closes #484, and does what it says! Recommended to hide whitespace during review...

Rename cluster column

---

bin/sce_qc_report.R
config/containers.config
external-instructions.md
internal-instructions.md
modules/export-anndata.nf
nextflow.config

Nothing new here, just syncing the version bumps and the minor formatting commits from #501 to `development`.

Sync v0.6.0 changes to development

---

lib/Utils.groovy

Nothing new here, just syncing the changes from #524 to `development`.

Sync changes to parse NA's to `development`

---

templates/qc_report/celltypes_supplemental_report.rmd

Closes #518 
This PR updates the CellAssign plot and text. I know I was supposed to bulletify the text, but it didn't seem like there was much to bullet, so I look forward to overhauling my text during review 😄
I don't have anything specific to say here other than, let me know what you think all around and we'll keep chipping away at plot styling!
Screenshot of updated section:

Replace CellAssign ridgeplots with density plots

---

references/celltype-reference-metadata.tsv

Closes #537 
This was pretty straight forward. I updated the name for the PanglaoDB reference to be `<organ>-compartment` as we discussed.

Update the reference name to include `-compartment`

---

external-instructions.md

This makes the changes I was suggesting in my slightly late review: https://github.com/AlexsLemonade/scpca-nf/pull/577#pullrequestreview-1735637935
While doing this I also caught some places the headings/links no longer matched.

Use words to describe files

---

bin/add_celltypes_to_sce.R
bin/cluster_sce.R

Here I'm making sure that we compress all of our output files. I'm going to make the same change to the cluster script on `main`.

Compress the RDS files

---

.pre-commit-config.yaml
bin/cluster_sce.R
external-instructions.md
internal-instructions.md
nextflow.config

This PR includes the update to the clustering script to be sure that the processed RDS files are compressed. 
I also used this opportunity to update the version tag so I can release these changes. 
The last thing that I was forced to do was cherry pick the addition of pre-commit. Without the config file it wouldn't let me commit anything...

Compress cluster output and update tag

---

references/README.md
test/README.md

Closes #561 
Here, I've added a README to `references`, and while I was here I added a little one into `test`, too. 
Please leave any phrasing suggestions! I haven't directly worked with the main workflow reference files, so extra-check my wording there.

Add README to references and test directories

---

bin/sce_to_anndata.R
config/containers.config
main.nf
templates/qc_report/main_qc_report.rmd

It looks like there were a few things that were in `main` that aren't in `development` that caused some conflicts. I can't directly push those changes to `development` because branch protection, so I'm fixing the conflicts here and also updating the container for `scpcaTools`.

Fix merge conflicts and update scpcaTools version

---

merge.nf

Related to #610 
What it says!

Swap in one more merge_project_id

---

config/process_base.config
config/profile_awsbatch_auto.config
config/profile_ccdl.config
modules/classify-celltypes.nf

Doing it properly this time... Made a branch from dev so I can do this without updating main!

Merge in CPU changes

---

bin/add_celltypes_to_sce.R
external-instructions.md
internal-instructions.md
lib/Utils.groovy
main.nf
modules/af-features.nf
modules/af-rna.nf
modules/bulk-salmon.nf
modules/cellsnp.nf
modules/classify-celltypes.nf
modules/spaceranger.nf
nextflow.config
templates/qc_report/celltypes_qc.rmd
templates/qc_report/celltypes_supplemental_report.rmd

Here I'm adding all of the commits we want in the next release from `development` to `main`. I cherry picked all the commits related to the PRs mentioned in #638 that were not already in `main`. 
I also updated the version strings in the config and instructions files. I'm doing a test run to make sure that this is all good to go and once that is set, I'll request review.

Sync changes for v0.7.1 release to `main`

---

bin/merge_sces.R
components/dictionary.txt
templates/merge-report.Rmd

Closes #625 
Stacked on #629 
Here I'm adding two separate sections that include summary tables. One for library statistics and one for sample statistics. 
- The library statistics section includes a table that summarizes the types of libraries, including tech and seq unit information. This table is shown for every single library type. 
- To account for ADT or multiplexed data, I added two separate tables that show the total number of libraries with/without ADT or multiplexed data. These are only shown if at least one library has adt or cellhash. 
- To detect if any libraries have ADT/multiplexing, I went back into the `merge_sces.R` script and added in an `additional_modalities` column to each SCE before merging. I use the names of the `altExp` in the original SCE objects to populate …

Add tables to merge report

---

merge.nf
modules/qc-report.nf

Parallel with https://github.com/AlexsLemonade/scpca-docs/issues/226 & https://github.com/AlexsLemonade/scpca-docs/issues/218 & , I made the following changes:
- supplemental cell type workflow: `_cell_type_report.html` -> `_celltype-report.html`
- [PENDING] merge workflow: `_summary_report.html` -> `_merged-summary-report.html` (edit to type arrows correctly........)
Filing as draft until [PENDING] is no longer [PENDING]!

Update qc report names

---

bin/merge_sces.R

Does what it says!
Since we aren't keeping clusters, we should not keep the cluster parameters. 
This PR was brought to you by me actually writing docs 💪 and realizing it would be super weird to document this.

Remove cluster metadata from SCE before merging

---

modules/spaceranger.nf

Closes #678 
Does what it says!
We now match: https://github.com/AlexsLemonade/scpca-docs/blob/1227fe904b37289035287b11011774d4cbbb0dcc/docs/images/spatial-download-folder.png

Rename spatial report with dash

---

bin/add_celltypes_to_sce.R
bin/predict_cellassign.py
bin/sce_to_anndata.R
external-instructions.md
internal-instructions.md
lib/Utils.groovy
modules/export-anndata.nf
nextflow.config

This PR just merges the current `main` branch into `development`, since we made some commits directly into `main` that never got back-ported.

Merge main code into development

---

.pre-commit-config.yaml

Here I am adding a line to show how to disable the autofixes by pre-commit.ci
I also updated the versions of a few hooks.

add autofix setting & update

---

external-instructions.md
internal-instructions.md
nextflow.config

Towards #748 
I just updated everything from v0.8.0 to v0.8.1 in preparation for the release.

Update tags to v0.8.1

---

config/containers.config
external-instructions.md
internal-instructions.md
nextflow.config

In preparation for #770, just changing the release tag in the docs and config.

Change version to v0.8.2

---

merge.nf

Same as #781 just for `main`. This one shouldn't have any conflicts.

Actually sync changes for counting libraries into `main`

---

merge.nf

Merged HVGS into `main`

---

external-instructions.md
internal-instructions.md
nextflow.config

part of #785
Updating the version numbers for the next release.

Update version numbers 

---

config/containers.config
external-instructions.md
internal-instructions.md
nextflow.config

Closes #792 
Closes #790 (as far as the workflow goes; the portal changes needed are tracked in https://github.com/AlexsLemonade/ScPCA-admin/issues/986
Here I am incorporating the latest versions of the `scpcaTools` images (which fixes a missing rounding bug #790) and bumping the workflow version number in preparation for #793

Use scpcatools 0.4.1 images

---

modules/export-anndata.nf
nextflow.config

closes #798
Does what the title says, and also fixes our use of a removed Nextflow option.
I have tested this and it seems to work with at least the cases I have found; I also tested that when there are 3 cells, variance is calculated, as is a PCA (with a complaint, of course).

Increase minimum cells to 3

---

external-instructions.md
internal-instructions.md
nextflow.config

In preparation for #810, this just updates the version tag.

Update version tag to v0.8.6

---

bin/merge_sces.R

Closes #840 
Here I am updating the script for merging SCEs to include the new columns added in #824. We should have one new column for the `cellassign_celltype_ontology` and then two new columns for consensus annotations. I added those columns to the list of expected columns and then updated some of the code we use for handling situations where not all libraries in an object have the same set of cell types. 
In doing this I was able to remove the list of celltype methods and just detect if cell types were annotated based on the names in the `colData`. This just meant deleting a few extra lines of code and moving some of the code up. 
I tested this with a few libraries where only 1 had consensus cell types and the expected columns were present and filled in appropriately. I also did a run …

Account for consensus columns in merged objects

---

docker/cellbrowser/Dockerfile

In #988 I failed to change anything that actually triggered the docker run. So here I am changing something minor.

slight docker change for triggers

---

docker/cellbrowser/Dockerfile

Trying to update flex again

---

components/dictionary.txt
config/ccdl_profiles.config
config/reference_paths.config
internal-instructions.md
references/README.md
references/broad-diagnosis-map.tsv
references/diagnosis-celltype-groups.tsv

Closes #1004 
This PR adds inferCNV docs to our `internal-instructions.md` doc, based on this list of topics I came up with: https://github.com/AlexsLemonade/scpca-nf/issues/1004#issuecomment-3299241943.
I also ensured that cnv calling is on in the staging/prod ccdl profiles.
Please let me know if anything is unclear and should be rephrased, or if you think I'm missing* anything!
Edit - there's TODOs in there for pending OpenScPCA release, so this PR could wait a lil for that to be ready, or I can come back add that info in when I finally copy in the diagnosis files in #1006

Add inferCNV internal instructions

---

main.nf
modules/call-cnvs.nf
modules/cellranger-flex.nf
modules/classify-celltypes.nf

While investigating https://github.com/AlexsLemonade/scpca-nf/pull/1026#issuecomment-3307756048, I was looking through my local copy of scpca-nf, and found one place where we aren't really tracking the `perform_celltyping` variable quite right in the workflow, so I fixed that, along with some other complaints that the linter was throwing at me.

Fix a few minor nextflow issues
